import { ActionCard } from '../models/types';

export const INVESTOR_CARDS: ActionCard[] = [
  {
    id: 'inv_01',
    roleId: 'investor',
    name: 'Sponsorship Deal',
    description: 'Secure corporate sponsorship for a zone in exchange for branding rights. Quick budget at the cost of future revenue share.',
    flavorText: 'The logo on the bench was small. The check was not.',
    baseValue: 3,
    cost: { influence: 1 },
    abilityCheck: { ability: 'resourcefulness', threshold: 10, skill: 'negotiation' },
    effects: [
      { type: 'add_resources', target: 'zone', params: { resources: { budget: 3 } } },
      { type: 'create_revenue_token', target: 'zone', params: { amount: 1 } },
    ],
    seriesPosition: 'starter',
    tags: ['commercial', 'funding', 'coalition'],
    artworkId: 'art_inv_sponsorship',
  },
  {
    id: 'inv_02',
    roleId: 'investor',
    name: 'Commercial Proposal',
    description: 'Propose a revenue-generating activity for a zone. Brings money in but may conflict with community values.',
    flavorText: 'Profit and purpose, walking the thinnest of lines.',
    baseValue: 4,
    cost: { budget: 2, influence: 1 },
    abilityCheck: { ability: 'resourcefulness', threshold: 12, skill: 'budgeting' },
    effects: [
      { type: 'add_progress_marker', target: 'zone', params: { count: 2 } },
      { type: 'create_revenue_token', target: 'zone', params: { amount: 1 } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
    ],
    seriesPosition: 'starter',
    tags: ['commercial', 'funding', 'construction'],
    artworkId: 'art_inv_commercial_proposal',
  },
  {
    id: 'inv_03',
    roleId: 'investor',
    name: 'Public-Private Partnership',
    description: 'Structure a deal combining public funds and private capital. Complex but high impact when it works.',
    flavorText: 'Two hands shaking: one in a suit, one in a kurta. Both needed what the other had.',
    baseValue: 4,
    cost: { budget: 3, influence: 1 },
    abilityCheck: { ability: 'resourcefulness', threshold: 12, skill: 'coalitionBuilding' },
    effects: [
      { type: 'add_progress_marker', target: 'zone', params: { count: 3 } },
      { type: 'grant_cp', target: 'all_players', params: { amount: 2 } },
      { type: 'modify_zone_condition', target: 'zone', params: { improvement: 1 } },
    ],
    seriesPosition: 'middle',
    tags: ['commercial', 'funding', 'coalition'],
    artworkId: 'art_inv_ppp',
  },
  {
    id: 'inv_04',
    roleId: 'investor',
    name: 'Market Analysis',
    description: 'Conduct a market study to identify the most economically viable improvements for a zone.',
    flavorText: 'The numbers told a story of untapped potential and cautious optimism.',
    baseValue: 2,
    cost: { budget: 1 },
    abilityCheck: { ability: 'resourcefulness', threshold: 10 },
    effects: [
      { type: 'reveal_zone_info', target: 'zone', params: { revealsEconomicViability: true, revealsROI: true } },
      { type: 'add_resources', target: 'self', params: { resources: { knowledge: 1 } } },
    ],
    seriesPosition: 'middle',
    tags: ['commercial', 'assessment', 'funding'],
    artworkId: 'art_inv_market_analysis',
  },
  {
    id: 'inv_05',
    roleId: 'investor',
    name: 'Equipment Donation',
    description: 'Donate surplus equipment or materials to a zone project. Tax-deductible and good for reputation.',
    flavorText: 'The warehouse had more than enough. The park had less than enough. Simple math.',
    baseValue: 2,
    cost: { budget: 1 },
    abilityCheck: null,
    effects: [
      { type: 'add_resources', target: 'zone', params: { resources: { material: 3 } } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
    ],
    seriesPosition: 'any',
    tags: ['funding', 'construction', 'community'],
    artworkId: 'art_inv_equipment',
  },
  {
    id: 'inv_06',
    roleId: 'investor',
    name: 'Vendor License',
    description: 'Formalize vendor operations in a zone with proper licensing and quality standards.',
    flavorText: 'Order from chaos. And a 10% licensing fee, naturally.',
    baseValue: 3,
    cost: { budget: 1, influence: 1 },
    abilityCheck: { ability: 'resourcefulness', threshold: 10, skill: 'negotiation' },
    effects: [
      { type: 'remove_problem_marker', target: 'zone', params: { count: 1, vendorRelated: true } },
      { type: 'create_revenue_token', target: 'zone', params: { amount: 1 } },
    ],
    seriesPosition: 'middle',
    tags: ['commercial', 'regulatory', 'governance'],
    artworkId: 'art_inv_vendor_license',
  },
  {
    id: 'inv_07',
    roleId: 'investor',
    name: 'Tourism Marketing',
    description: 'Launch a marketing campaign to attract visitors and tourists to the park. More footfall means more revenue.',
    flavorText: 'The brochure made the park look like paradise. Now they just had to make it true.',
    baseValue: 3,
    cost: { budget: 2 },
    abilityCheck: { ability: 'resourcefulness', threshold: 11 },
    effects: [
      { type: 'add_progress_marker', target: 'zone', params: { count: 2 } },
      { type: 'add_resources', target: 'self', params: { resources: { influence: 1, budget: 1 } } },
    ],
    seriesPosition: 'middle',
    tags: ['commercial', 'community', 'communication'],
    artworkId: 'art_inv_tourism',
  },
  {
    id: 'inv_08',
    roleId: 'investor',
    name: 'Infrastructure Investment',
    description: 'Commit major capital to a large-scale infrastructure improvement. The biggest moves require the biggest budgets.',
    flavorText: 'The check had many zeros. So did the potential return.',
    baseValue: 4,
    cost: { budget: 4 },
    abilityCheck: { ability: 'resourcefulness', threshold: 13, skill: 'budgeting' },
    effects: [
      { type: 'modify_zone_condition', target: 'zone', params: { improvement: 2 } },
      { type: 'add_progress_marker', target: 'zone', params: { count: 3 } },
      { type: 'create_revenue_token', target: 'zone', params: { amount: 1 } },
    ],
    seriesPosition: 'closer',
    tags: ['funding', 'construction', 'commercial'],
    artworkId: 'art_inv_infrastructure',
  },
  {
    id: 'inv_09',
    roleId: 'investor',
    name: 'Micro-Loan Program',
    description: 'Establish a micro-loan fund for small-scale community improvements. Empowers others while maintaining oversight.',
    flavorText: 'Small loans, big dreams. And a reasonable interest rate.',
    baseValue: 2,
    cost: { budget: 2 },
    abilityCheck: { ability: 'resourcefulness', threshold: 9 },
    effects: [
      { type: 'grant_tokens_to_other', target: 'other_player', params: { resources: { budget: 2 } } },
      { type: 'grant_cp', target: 'self', params: { amount: 2 } },
    ],
    seriesPosition: 'middle',
    tags: ['funding', 'community', 'coalition'],
    artworkId: 'art_inv_microloan',
  },
  {
    id: 'inv_10',
    roleId: 'investor',
    name: 'Revenue Projection',
    description: 'Calculate potential returns on zone investments. Helps prioritize where money goes.',
    flavorText: 'The spreadsheet predicted profit. History suggested caution.',
    baseValue: 2,
    cost: { budget: 1 },
    abilityCheck: { ability: 'resourcefulness', threshold: 10 },
    effects: [
      { type: 'reveal_zone_info', target: 'zone', params: { revealsROI: true, revealsRevenuePotential: true } },
      { type: 'add_resources', target: 'self', params: { resources: { knowledge: 1 } } },
    ],
    seriesPosition: 'middle',
    tags: ['commercial', 'assessment', 'funding'],
    artworkId: 'art_inv_revenue_projection',
  },
  {
    id: 'inv_11',
    roleId: 'investor',
    name: 'Maintenance Outsourcing',
    description: 'Contract a private firm for ongoing zone maintenance. Reliable but costs budget each round.',
    flavorText: 'Outsource the problem, not the responsibility. At least, that was the plan.',
    baseValue: 3,
    cost: { budget: 2 },
    abilityCheck: { ability: 'resourcefulness', threshold: 10, skill: 'budgeting' },
    effects: [
      { type: 'remove_problem_marker', target: 'zone', params: { count: 1 } },
      { type: 'apply_status_effect', target: 'zone', params: { name: 'contracted_maintenance', duration: 3, description: 'Professional maintenance reduces degradation' } },
    ],
    seriesPosition: 'any',
    tags: ['commercial', 'maintenance', 'construction'],
    artworkId: 'art_inv_outsourcing',
  },
  {
    id: 'inv_12',
    roleId: 'investor',
    name: 'Brand Sponsorship',
    description: 'Attract a brand sponsor for cosmetic zone improvements. Looks good, generates modest budget.',
    flavorText: 'The new paint job was courtesy of a cola company. Beggars and choosers.',
    baseValue: 2,
    cost: { influence: 1 },
    abilityCheck: null,
    effects: [
      { type: 'add_resources', target: 'self', params: { resources: { budget: 2 } } },
      { type: 'add_progress_marker', target: 'zone', params: { count: 1 } },
    ],
    seriesPosition: 'middle',
    tags: ['commercial', 'funding', 'community'],
    artworkId: 'art_inv_brand',
  },
  {
    id: 'inv_13',
    roleId: 'investor',
    name: 'Real Estate Assessment',
    description: 'Evaluate the development potential of a zone. Knowledge is the first step to smart investment.',
    flavorText: 'Location, location, location. And also: permits, permits, permits.',
    baseValue: 2,
    cost: { budget: 1 },
    abilityCheck: { ability: 'resourcefulness', threshold: 9 },
    effects: [
      { type: 'reveal_zone_info', target: 'zone', params: { revealsDevelopmentPotential: true } },
      { type: 'add_resources', target: 'self', params: { resources: { knowledge: 1, influence: 1 } } },
    ],
    seriesPosition: 'starter',
    tags: ['assessment', 'commercial', 'construction'],
    artworkId: 'art_inv_real_estate',
  },
  {
    id: 'inv_14',
    roleId: 'investor',
    name: 'Cost Optimization',
    description: 'Find ways to reduce project costs without cutting corners. Efficiency is an art form.',
    flavorText: 'The same result for 30% less. The accountant wept with joy.',
    baseValue: 3,
    cost: { knowledge: 1 },
    abilityCheck: { ability: 'resourcefulness', threshold: 11, skill: 'budgeting' },
    effects: [
      { type: 'add_resources', target: 'self', params: { resources: { budget: 2, material: 1 } } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
    ],
    seriesPosition: 'middle',
    tags: ['funding', 'construction', 'design'],
    artworkId: 'art_inv_cost_opt',
  },
  {
    id: 'inv_15',
    roleId: 'investor',
    name: 'Bulk Material Purchase',
    description: 'Buy construction materials in bulk at a discount. Economies of scale benefit everyone.',
    flavorText: 'A truckload of cement and the promise of progress.',
    baseValue: 3,
    cost: { budget: 3 },
    abilityCheck: null,
    effects: [
      { type: 'add_resources', target: 'self', params: { resources: { material: 5 } } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
    ],
    seriesPosition: 'any',
    tags: ['funding', 'construction', 'maintenance'],
    artworkId: 'art_inv_bulk_material',
  },
  {
    id: 'inv_16',
    roleId: 'investor',
    name: 'Exit Strategy',
    description: 'Cash out revenue tokens from a zone for immediate budget. Sometimes it is time to take profits.',
    flavorText: 'The investment had matured. Time to harvest.',
    baseValue: 3,
    cost: {},
    abilityCheck: { ability: 'resourcefulness', threshold: 10 },
    effects: [
      { type: 'add_resources', target: 'self', params: { resources: { budget: 4 }, consumesRevenueToken: true } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
    ],
    seriesPosition: 'closer',
    tags: ['commercial', 'funding', 'assessment'],
    artworkId: 'art_inv_exit_strategy',
  },
];
