import { ActionCard } from '../models/types';

export const ADMINISTRATOR_CARDS: ActionCard[] = [
  {
    id: 'adm_01',
    roleId: 'administrator',
    name: 'Budget Allocation',
    description: 'Redirect municipal funds to a priority zone. Provides immediate budget support but requires political will.',
    flavorText: 'The council approved the allocation, though not without heated debate.',
    baseValue: 3,
    cost: { influence: 1 },
    abilityCheck: { ability: 'authority', threshold: 10, skill: 'budgeting' },
    effects: [
      { type: 'add_resources', target: 'zone', params: { resources: { budget: 3 } } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
    ],
    seriesPosition: 'starter',
    tags: ['regulatory', 'funding', 'governance'],
    artworkId: 'art_adm_budget_allocation',
  },
  {
    id: 'adm_02',
    roleId: 'administrator',
    name: 'Regulatory Inspection',
    description: 'Order an official inspection of a zone, revealing hidden problems and enforcing compliance standards.',
    flavorText: 'The inspector arrived unannounced. Nobody was ready.',
    baseValue: 2,
    cost: { budget: 1 },
    abilityCheck: { ability: 'authority', threshold: 9 },
    effects: [
      { type: 'reveal_zone_info', target: 'zone', params: { revealsProblems: true, revealsResources: true } },
      { type: 'remove_problem_marker', target: 'zone', params: { count: 1 } },
    ],
    seriesPosition: 'starter',
    tags: ['regulatory', 'assessment', 'governance'],
    artworkId: 'art_adm_regulatory_inspection',
  },
  {
    id: 'adm_03',
    roleId: 'administrator',
    name: 'Emergency Repair Order',
    description: 'Fast-track maintenance work on a critical zone. Bypasses normal approval processes.',
    flavorText: 'Red tape burns well when the situation is desperate enough.',
    baseValue: 3,
    cost: { budget: 2 },
    abilityCheck: { ability: 'authority', threshold: 11 },
    effects: [
      { type: 'modify_zone_condition', target: 'zone', params: { improvement: 1 } },
      { type: 'remove_problem_marker', target: 'zone', params: { count: 1 } },
    ],
    seriesPosition: 'middle',
    tags: ['maintenance', 'regulatory', 'construction'],
    artworkId: 'art_adm_emergency_repair',
  },
  {
    id: 'adm_04',
    roleId: 'administrator',
    name: 'Public Notice',
    description: 'Issue an official notice to address a community concern. Boosts trust if followed through.',
    flavorText: 'The notice went up on every lamppost in the park.',
    baseValue: 2,
    cost: { budget: 1 },
    abilityCheck: null,
    effects: [
      { type: 'modify_ability_temp', target: 'self', params: { ability: 'communityTrust', modifier: 2, duration: 1 } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
    ],
    seriesPosition: 'any',
    tags: ['community', 'governance', 'communication'],
    artworkId: 'art_adm_public_notice',
  },
  {
    id: 'adm_05',
    roleId: 'administrator',
    name: 'Interdepartmental Coordination',
    description: 'Coordinate multiple government departments to tackle a complex issue. Slow but effective.',
    flavorText: 'Getting three departments to agree was harder than solving the actual problem.',
    baseValue: 4,
    cost: { budget: 2, influence: 1 },
    abilityCheck: { ability: 'politicalLeverage', threshold: 12, skill: 'coalitionBuilding' },
    effects: [
      { type: 'add_progress_marker', target: 'zone', params: { count: 3 } },
      { type: 'grant_cp', target: 'self', params: { amount: 2 } },
    ],
    seriesPosition: 'closer',
    tags: ['governance', 'coalition', 'regulatory'],
    artworkId: 'art_adm_interdept',
  },
  {
    id: 'adm_06',
    roleId: 'administrator',
    name: 'Permit Approval',
    description: 'Grant official permits for development or improvement work in a zone. Unlocks construction actions.',
    flavorText: 'Stamp. Sign. File. The wheels of bureaucracy turn slowly but surely.',
    baseValue: 3,
    cost: { influence: 1 },
    abilityCheck: { ability: 'authority', threshold: 10, skill: 'regulatoryNavigation' },
    effects: [
      { type: 'add_progress_marker', target: 'zone', params: { count: 2 } },
      { type: 'grant_cp', target: 'all_players', params: { amount: 1 } },
    ],
    seriesPosition: 'starter',
    tags: ['regulatory', 'construction', 'governance'],
    artworkId: 'art_adm_permit',
  },
  {
    id: 'adm_07',
    roleId: 'administrator',
    name: 'Tax Incentive Program',
    description: 'Offer tax breaks to attract private investment into the park. Benefits the Investor but generates goodwill.',
    flavorText: 'A small break for business, a big step for the park.',
    baseValue: 3,
    cost: { budget: 1 },
    abilityCheck: { ability: 'politicalLeverage', threshold: 10, skill: 'budgeting' },
    effects: [
      { type: 'grant_tokens_to_other', target: 'other_player', params: { roleId: 'investor', resources: { budget: 2 } } },
      { type: 'grant_cp', target: 'self', params: { amount: 2 } },
    ],
    seriesPosition: 'middle',
    tags: ['funding', 'commercial', 'coalition'],
    artworkId: 'art_adm_tax_incentive',
  },
  {
    id: 'adm_08',
    roleId: 'administrator',
    name: 'Public Hearing',
    description: 'Hold a formal public hearing on a contested issue. Gives all players a voice but outcome depends on persuasion.',
    flavorText: 'The microphone was open to all. Not everyone was happy about that.',
    baseValue: 3,
    cost: { budget: 1, influence: 1 },
    abilityCheck: { ability: 'communityTrust', threshold: 11, skill: 'coalitionBuilding' },
    effects: [
      { type: 'grant_cp', target: 'all_players', params: { amount: 1 } },
      { type: 'modify_ability_temp', target: 'self', params: { ability: 'communityTrust', modifier: 2, duration: 2 } },
    ],
    seriesPosition: 'middle',
    tags: ['community', 'governance', 'negotiation'],
    artworkId: 'art_adm_public_hearing',
  },
  {
    id: 'adm_09',
    roleId: 'administrator',
    name: 'Enforcement Action',
    description: 'Crack down on violations in a zone. Effective but may alienate some stakeholders.',
    flavorText: 'The fines were steep, but the message was clear.',
    baseValue: 3,
    cost: { influence: 1 },
    abilityCheck: { ability: 'authority', threshold: 12, skill: 'regulatoryNavigation' },
    effects: [
      { type: 'remove_problem_marker', target: 'zone', params: { count: 2 } },
      { type: 'modify_ability_temp', target: 'self', params: { ability: 'communityTrust', modifier: -1, duration: 1 } },
    ],
    seriesPosition: 'closer',
    tags: ['regulatory', 'maintenance', 'governance'],
    artworkId: 'art_adm_enforcement',
  },
  {
    id: 'adm_10',
    roleId: 'administrator',
    name: 'Grant Application Support',
    description: 'Provide official backing for a grant application, increasing its chances of success.',
    flavorText: 'The letterhead of the municipality carried more weight than any argument.',
    baseValue: 2,
    cost: { budget: 1 },
    abilityCheck: { ability: 'authority', threshold: 9 },
    effects: [
      { type: 'grant_tokens_to_other', target: 'other_player', params: { resources: { budget: 2, knowledge: 1 } } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
    ],
    seriesPosition: 'middle',
    tags: ['funding', 'coalition', 'governance'],
    artworkId: 'art_adm_grant_support',
  },
  {
    id: 'adm_11',
    roleId: 'administrator',
    name: 'Zone Rezoning',
    description: 'Officially reclassify a zone to allow different types of development. Controversial but opens new possibilities.',
    flavorText: 'What was once parkland could become so much more. Or so much less.',
    baseValue: 4,
    cost: { influence: 2 },
    abilityCheck: { ability: 'politicalLeverage', threshold: 13, skill: 'regulatoryNavigation' },
    effects: [
      { type: 'modify_zone_condition', target: 'zone', params: { improvement: 1 } },
      { type: 'add_progress_marker', target: 'zone', params: { count: 2 } },
    ],
    seriesPosition: 'closer',
    tags: ['regulatory', 'construction', 'design'],
    artworkId: 'art_adm_rezoning',
  },
  {
    id: 'adm_12',
    roleId: 'administrator',
    name: 'Staff Deployment',
    description: 'Assign municipal workers to a zone for immediate maintenance and cleanup work.',
    flavorText: 'The crew arrived at dawn, armed with brooms and determination.',
    baseValue: 2,
    cost: { budget: 2 },
    abilityCheck: null,
    effects: [
      { type: 'add_progress_marker', target: 'zone', params: { count: 2 } },
      { type: 'generate_volunteers', target: 'zone', params: { count: 1 } },
    ],
    seriesPosition: 'any',
    tags: ['maintenance', 'construction', 'governance'],
    artworkId: 'art_adm_staff_deploy',
  },
  {
    id: 'adm_13',
    roleId: 'administrator',
    name: 'Media Briefing',
    description: 'Hold a press conference to shape public narrative about park improvements. Builds political capital.',
    flavorText: 'The cameras rolled. The Administrator smiled. The headlines wrote themselves.',
    baseValue: 2,
    cost: { budget: 1 },
    abilityCheck: { ability: 'politicalLeverage', threshold: 10 },
    effects: [
      { type: 'add_resources', target: 'self', params: { resources: { influence: 2 } } },
      { type: 'modify_ability_temp', target: 'self', params: { ability: 'politicalLeverage', modifier: 2, duration: 1 } },
    ],
    seriesPosition: 'any',
    tags: ['communication', 'governance', 'community'],
    artworkId: 'art_adm_media_briefing',
  },
  {
    id: 'adm_14',
    roleId: 'administrator',
    name: 'Vendor Licensing Reform',
    description: 'Overhaul the vendor licensing system to improve quality and reduce encroachment. A signature policy initiative.',
    flavorText: 'New rules, new permits, new opportunities. Some vendors grumbled, others flourished.',
    baseValue: 3,
    cost: { budget: 2, influence: 1 },
    abilityCheck: { ability: 'authority', threshold: 12, skill: 'regulatoryNavigation' },
    effects: [
      { type: 'remove_problem_marker', target: 'zone', params: { count: 2 } },
      { type: 'add_resources', target: 'zone', params: { resources: { budget: 2 } } },
    ],
    seriesPosition: 'closer',
    tags: ['regulatory', 'commercial', 'governance'],
    artworkId: 'art_adm_vendor_reform',
  },
  {
    id: 'adm_15',
    roleId: 'administrator',
    name: 'Safety Audit Order',
    description: 'Commission an official safety audit of park infrastructure. May reveal problems but also unlocks repair funding.',
    flavorText: 'The report was 47 pages long. None of it was good news. But at least now they knew.',
    baseValue: 2,
    cost: { budget: 1 },
    abilityCheck: { ability: 'authority', threshold: 9 },
    effects: [
      { type: 'reveal_zone_info', target: 'zone', params: { revealsProblems: true, revealsSafety: true } },
      { type: 'add_resources', target: 'self', params: { resources: { knowledge: 1 } } },
    ],
    seriesPosition: 'starter',
    tags: ['assessment', 'regulatory', 'maintenance'],
    artworkId: 'art_adm_safety_audit',
  },
  {
    id: 'adm_16',
    roleId: 'administrator',
    name: 'Mayoral Decree',
    description: 'Issue a special decree from the highest municipal authority. Powerful but spends significant political capital.',
    flavorText: 'When the Mayor speaks, even the trees seem to listen.',
    baseValue: 5,
    cost: { influence: 3 },
    abilityCheck: { ability: 'politicalLeverage', threshold: 14, skill: 'coalitionBuilding' },
    effects: [
      { type: 'modify_zone_condition', target: 'zone', params: { improvement: 2 } },
      { type: 'grant_cp', target: 'all_players', params: { amount: 2 } },
      { type: 'remove_problem_marker', target: 'zone', params: { count: 2 } },
    ],
    seriesPosition: 'closer',
    tags: ['governance', 'regulatory', 'coalition'],
    artworkId: 'art_adm_mayoral_decree',
  },
];
