import { ActionCard } from '../models/types';

export const DESIGNER_CARDS: ActionCard[] = [
  {
    id: 'des_01',
    roleId: 'designer',
    name: 'Design Proposal',
    description: 'Present a comprehensive design concept for a zone. High impact when accepted, but requires technical expertise to pull off.',
    flavorText: 'The blueprints unfurled across the table like a promise waiting to be kept.',
    baseValue: 4,
    cost: { knowledge: 2 },
    abilityCheck: { ability: 'technicalKnowledge', threshold: 12, skill: 'designThinking' },
    effects: [
      { type: 'add_progress_marker', target: 'zone', params: { count: 3 } },
      { type: 'grant_cp', target: 'self', params: { amount: 2 } },
    ],
    seriesPosition: 'starter',
    tags: ['design', 'construction', 'ecological'],
    artworkId: 'art_des_design_proposal',
  },
  {
    id: 'des_02',
    roleId: 'designer',
    name: 'Feasibility Study',
    description: 'Conduct a thorough analysis of costs, risks, and benefits for a proposed project. Reveals hidden information.',
    flavorText: 'Numbers do not lie, but they can certainly surprise.',
    baseValue: 2,
    cost: { knowledge: 1 },
    abilityCheck: { ability: 'technicalKnowledge', threshold: 10 },
    effects: [
      { type: 'reveal_zone_info', target: 'zone', params: { revealsProblems: true, revealsCosts: true } },
      { type: 'add_resources', target: 'self', params: { resources: { knowledge: 1 } } },
    ],
    seriesPosition: 'middle',
    tags: ['assessment', 'design', 'governance'],
    artworkId: 'art_des_feasibility',
  },
  {
    id: 'des_03',
    roleId: 'designer',
    name: 'Adaptive Reuse Plan',
    description: 'Redesign an existing structure or zone for a new purpose. Cheaper than building new and preserves heritage.',
    flavorText: 'What others see as ruins, the designer sees as raw material.',
    baseValue: 3,
    cost: { knowledge: 1, material: 1 },
    abilityCheck: { ability: 'technicalKnowledge', threshold: 11, skill: 'designThinking' },
    effects: [
      { type: 'modify_zone_condition', target: 'zone', params: { improvement: 1 } },
      { type: 'add_progress_marker', target: 'zone', params: { count: 2 } },
    ],
    seriesPosition: 'middle',
    tags: ['design', 'construction', 'community'],
    artworkId: 'art_des_adaptive_reuse',
  },
  {
    id: 'des_04',
    roleId: 'designer',
    name: 'Green Infrastructure Overlay',
    description: 'Integrate sustainable drainage, green roofs, or permeable surfaces into a zone design. Ecological and functional.',
    flavorText: 'Nature has been engineering solutions for millennia. We just need to listen.',
    baseValue: 3,
    cost: { knowledge: 1, material: 1 },
    abilityCheck: { ability: 'technicalKnowledge', threshold: 11, skill: 'environmentalAssessment' },
    effects: [
      { type: 'add_progress_marker', target: 'zone', params: { count: 2 } },
      { type: 'remove_problem_marker', target: 'zone', params: { count: 1 } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
    ],
    seriesPosition: 'middle',
    tags: ['ecological', 'design', 'construction'],
    artworkId: 'art_des_green_infra',
  },
  {
    id: 'des_05',
    roleId: 'designer',
    name: 'Structural Assessment',
    description: 'Evaluate the structural integrity of existing facilities. May reveal hidden problems or confirm safety.',
    flavorText: 'The cracks told a story that the paint had tried to hide.',
    baseValue: 2,
    cost: { knowledge: 1 },
    abilityCheck: { ability: 'technicalKnowledge', threshold: 10 },
    effects: [
      { type: 'reveal_zone_info', target: 'zone', params: { revealsProblems: true, revealsStructural: true } },
      { type: 'add_resources', target: 'self', params: { resources: { knowledge: 1 } } },
    ],
    seriesPosition: 'middle',
    tags: ['assessment', 'maintenance', 'design'],
    artworkId: 'art_des_structural',
  },
  {
    id: 'des_06',
    roleId: 'designer',
    name: 'Master Plan',
    description: 'Present a comprehensive master plan that ties multiple zone improvements together. Most effective as part of a long series.',
    flavorText: 'A single zone is a project. A master plan is a legacy.',
    baseValue: 5,
    cost: { knowledge: 2, material: 1 },
    abilityCheck: { ability: 'technicalKnowledge', threshold: 14, skill: 'designThinking' },
    effects: [
      { type: 'modify_zone_condition', target: 'zone', params: { improvement: 2 } },
      { type: 'grant_cp', target: 'all_players', params: { amount: 2 } },
      { type: 'add_progress_marker', target: 'zone', params: { count: 3 } },
    ],
    seriesPosition: 'closer',
    tags: ['design', 'construction', 'coalition'],
    artworkId: 'art_des_master_plan',
  },
  {
    id: 'des_07',
    roleId: 'designer',
    name: 'Material Specification',
    description: 'Source and specify the right materials for a construction project. Ensures quality and reduces waste.',
    flavorText: 'The difference between a bench that lasts a year and one that lasts a decade is in the specification.',
    baseValue: 2,
    cost: { knowledge: 1 },
    abilityCheck: { ability: 'technicalKnowledge', threshold: 9 },
    effects: [
      { type: 'add_resources', target: 'self', params: { resources: { material: 2 } } },
      { type: 'add_progress_marker', target: 'zone', params: { count: 1 } },
    ],
    seriesPosition: 'middle',
    tags: ['construction', 'design', 'maintenance'],
    artworkId: 'art_des_material_spec',
  },
  {
    id: 'des_08',
    roleId: 'designer',
    name: 'Community Design Workshop',
    description: 'Host a participatory design session with local residents. Builds trust and generates collaborative ideas.',
    flavorText: 'The best designs come from listening to the people who will use them.',
    baseValue: 3,
    cost: { knowledge: 1 },
    abilityCheck: { ability: 'communityTrust', threshold: 10 },
    effects: [
      { type: 'grant_cp', target: 'self', params: { amount: 2 } },
      { type: 'modify_ability_temp', target: 'self', params: { ability: 'communityTrust', modifier: 2, duration: 2 } },
      { type: 'generate_volunteers', target: 'zone', params: { count: 2 } },
    ],
    seriesPosition: 'middle',
    tags: ['community', 'design', 'negotiation'],
    artworkId: 'art_des_workshop',
  },
  {
    id: 'des_09',
    roleId: 'designer',
    name: 'Accessibility Audit',
    description: 'Evaluate and improve universal accessibility of a zone. Bonus effectiveness for utility zones.',
    flavorText: 'A park for everyone means exactly that. Everyone.',
    baseValue: 2,
    cost: { knowledge: 1 },
    abilityCheck: { ability: 'technicalKnowledge', threshold: 10 },
    effects: [
      { type: 'add_progress_marker', target: 'zone', params: { count: 2, bonusForUtility: 1 } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
    ],
    seriesPosition: 'middle',
    tags: ['assessment', 'community', 'design'],
    artworkId: 'art_des_accessibility',
  },
  {
    id: 'des_10',
    roleId: 'designer',
    name: 'Landscape Redesign',
    description: 'Completely reimagine the landscaping of a zone. Transforms appearance and functionality.',
    flavorText: 'Where there was concrete, there will be green. Where there was neglect, there will be beauty.',
    baseValue: 3,
    cost: { material: 2, knowledge: 1 },
    abilityCheck: { ability: 'technicalKnowledge', threshold: 12, skill: 'designThinking' },
    effects: [
      { type: 'modify_zone_condition', target: 'zone', params: { improvement: 1 } },
      { type: 'remove_problem_marker', target: 'zone', params: { count: 1 } },
      { type: 'add_progress_marker', target: 'zone', params: { count: 2 } },
    ],
    seriesPosition: 'closer',
    tags: ['design', 'ecological', 'construction'],
    artworkId: 'art_des_landscape',
  },
  {
    id: 'des_11',
    roleId: 'designer',
    name: 'Quick Patch',
    description: 'Apply a temporary but immediate fix to an urgent problem. Not elegant, but effective in a crisis.',
    flavorText: 'Sometimes good enough right now beats perfect next month.',
    baseValue: 2,
    cost: { material: 1 },
    abilityCheck: null,
    effects: [
      { type: 'remove_problem_marker', target: 'zone', params: { count: 1 } },
      { type: 'add_progress_marker', target: 'zone', params: { count: 1 } },
    ],
    seriesPosition: 'any',
    tags: ['maintenance', 'construction', 'design'],
    artworkId: 'art_des_quick_patch',
  },
  {
    id: 'des_12',
    roleId: 'designer',
    name: 'Prototype Installation',
    description: 'Install a small-scale prototype to test a design concept. Low risk, moderate reward.',
    flavorText: 'Build it small, learn what works, then scale it up.',
    baseValue: 3,
    cost: { material: 1, knowledge: 1 },
    abilityCheck: { ability: 'technicalKnowledge', threshold: 10 },
    effects: [
      { type: 'add_progress_marker', target: 'zone', params: { count: 2 } },
      { type: 'add_resources', target: 'self', params: { resources: { knowledge: 1 } } },
    ],
    seriesPosition: 'starter',
    tags: ['design', 'construction', 'assessment'],
    artworkId: 'art_des_prototype',
  },
  {
    id: 'des_13',
    roleId: 'designer',
    name: 'Site Survey',
    description: 'Conduct a thorough survey of a zone to understand its current state, constraints, and potential.',
    flavorText: 'Measure twice, design once.',
    baseValue: 2,
    cost: { knowledge: 1 },
    abilityCheck: { ability: 'technicalKnowledge', threshold: 9 },
    effects: [
      { type: 'reveal_zone_info', target: 'zone', params: { revealsAll: true } },
      { type: 'add_resources', target: 'self', params: { resources: { knowledge: 1 } } },
    ],
    seriesPosition: 'starter',
    tags: ['assessment', 'design', 'ecological'],
    artworkId: 'art_des_site_survey',
  },
  {
    id: 'des_14',
    roleId: 'designer',
    name: 'Construction Supervision',
    description: 'Oversee construction work to ensure quality standards are met. Prevents rework and waste.',
    flavorText: 'Without supervision, the cheapest option always wins. And then breaks.',
    baseValue: 3,
    cost: { knowledge: 1 },
    abilityCheck: { ability: 'technicalKnowledge', threshold: 11 },
    effects: [
      { type: 'add_progress_marker', target: 'zone', params: { count: 2 } },
      { type: 'modify_zone_condition', target: 'zone', params: { improvement: 1 } },
    ],
    seriesPosition: 'closer',
    tags: ['construction', 'maintenance', 'design'],
    artworkId: 'art_des_supervision',
  },
  {
    id: 'des_15',
    roleId: 'designer',
    name: 'Innovation Grant',
    description: 'Apply for and receive funding for innovative design solutions. Generates knowledge and budget.',
    flavorText: 'Innovation is just another word for solving old problems in new ways.',
    baseValue: 3,
    cost: { knowledge: 1 },
    abilityCheck: { ability: 'adaptability', threshold: 11 },
    effects: [
      { type: 'add_resources', target: 'self', params: { resources: { knowledge: 2, budget: 1 } } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
    ],
    seriesPosition: 'any',
    tags: ['funding', 'design', 'ecological'],
    artworkId: 'art_des_innovation',
  },
  {
    id: 'des_16',
    roleId: 'designer',
    name: 'Sustainability Certificate',
    description: 'Achieve an environmental certification for a zone design. Provides ongoing ecological bonuses.',
    flavorText: 'The plaque read: "Certified Sustainable." It was more than a label; it was a commitment.',
    baseValue: 3,
    cost: { knowledge: 2 },
    abilityCheck: { ability: 'technicalKnowledge', threshold: 12, skill: 'environmentalAssessment' },
    effects: [
      { type: 'add_progress_marker', target: 'zone', params: { count: 2, ecoBonus: true } },
      { type: 'grant_cp', target: 'self', params: { amount: 2 } },
      { type: 'modify_zone_condition', target: 'zone', params: { improvement: 1 } },
    ],
    seriesPosition: 'closer',
    tags: ['ecological', 'design', 'assessment'],
    artworkId: 'art_des_sustainability',
  },
];
