import { ActionCard } from '../models/types';

export const ADVOCATE_CARDS: ActionCard[] = [
  {
    id: 'adv_01',
    roleId: 'advocate',
    name: 'Environmental Impact Report',
    description: 'Prepare a detailed environmental impact assessment. Can block or modify projects that would harm ecology.',
    flavorText: 'The data was irrefutable. The pond was dying, and everyone needed to know.',
    baseValue: 3,
    cost: { knowledge: 1 },
    abilityCheck: { ability: 'technicalKnowledge', threshold: 10, skill: 'environmentalAssessment' },
    effects: [
      { type: 'reveal_zone_info', target: 'zone', params: { revealsEcologicalImpact: true } },
      { type: 'block_action', target: 'zone', params: { blockHarmfulProjects: true } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
    ],
    seriesPosition: 'starter',
    tags: ['ecological', 'assessment', 'governance'],
    artworkId: 'art_adv_eir',
  },
  {
    id: 'adv_02',
    roleId: 'advocate',
    name: 'Grant Application',
    description: 'Apply for external funding from environmental or social development agencies. Takes time but brings free resources.',
    flavorText: 'The grant was competitive. Twelve pages of justification for twelve weeks of waiting.',
    baseValue: 3,
    cost: { knowledge: 1, influence: 1 },
    abilityCheck: { ability: 'communityTrust', threshold: 11, skill: 'coalitionBuilding' },
    effects: [
      { type: 'add_resources', target: 'self', params: { resources: { budget: 4 }, delayed: true, delayRounds: 1 } },
      { type: 'grant_cp', target: 'self', params: { amount: 2 } },
    ],
    seriesPosition: 'any',
    tags: ['funding', 'ecological', 'community'],
    artworkId: 'art_adv_grant',
  },
  {
    id: 'adv_03',
    roleId: 'advocate',
    name: 'Awareness Campaign',
    description: 'Launch a public awareness campaign about an environmental or social issue. Changes how people see the park.',
    flavorText: 'The posters went up overnight. By morning, the conversation had changed.',
    baseValue: 3,
    cost: { influence: 1, knowledge: 1 },
    abilityCheck: { ability: 'communityTrust', threshold: 10, skill: 'publicSpeaking' },
    effects: [
      { type: 'modify_ability_temp', target: 'all_players', params: { ability: 'communityTrust', modifier: 1, duration: 2 } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
      { type: 'add_progress_marker', target: 'zone', params: { count: 1 } },
    ],
    seriesPosition: 'middle',
    tags: ['community', 'ecological', 'communication'],
    artworkId: 'art_adv_awareness',
  },
  {
    id: 'adv_04',
    roleId: 'advocate',
    name: 'Heritage Preservation Claim',
    description: 'File a heritage preservation claim to protect a zone from harmful development. Legal protection through cultural significance.',
    flavorText: 'This garden was planted by freedom fighters. Some things are more valuable than development.',
    baseValue: 3,
    cost: { knowledge: 1, influence: 1 },
    abilityCheck: { ability: 'politicalLeverage', threshold: 11, skill: 'environmentalAssessment' },
    effects: [
      { type: 'block_action', target: 'zone', params: { blockDevelopment: true, duration: 2 } },
      { type: 'add_progress_marker', target: 'zone', params: { count: 1 } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
    ],
    seriesPosition: 'middle',
    tags: ['ecological', 'governance', 'community'],
    artworkId: 'art_adv_heritage',
  },
  {
    id: 'adv_05',
    roleId: 'advocate',
    name: 'Biodiversity Audit',
    description: 'Catalog the flora and fauna in a zone. Reveals ecological value and may unlock conservation funding.',
    flavorText: 'Seventeen species of butterfly. Four varieties of medicinal herbs. One endangered frog.',
    baseValue: 2,
    cost: { knowledge: 1 },
    abilityCheck: { ability: 'technicalKnowledge', threshold: 10, skill: 'environmentalAssessment' },
    effects: [
      { type: 'reveal_zone_info', target: 'zone', params: { revealsBiodiversity: true, revealsEcoValue: true } },
      { type: 'add_resources', target: 'self', params: { resources: { knowledge: 1 } } },
    ],
    seriesPosition: 'middle',
    tags: ['ecological', 'assessment', 'design'],
    artworkId: 'art_adv_biodiversity',
  },
  {
    id: 'adv_06',
    roleId: 'advocate',
    name: 'Water Quality Test',
    description: 'Test water quality in the boating pond and surrounding areas. Essential for understanding the algae bloom crisis.',
    flavorText: 'The pH levels told a story of neglect. The dissolved oxygen told a story of urgency.',
    baseValue: 2,
    cost: { knowledge: 1 },
    abilityCheck: { ability: 'technicalKnowledge', threshold: 9 },
    effects: [
      { type: 'reveal_zone_info', target: 'zone', params: { revealsWaterQuality: true, revealsProblems: true } },
      { type: 'add_resources', target: 'self', params: { resources: { knowledge: 1 } } },
    ],
    seriesPosition: 'starter',
    tags: ['ecological', 'assessment', 'maintenance'],
    artworkId: 'art_adv_water_test',
  },
  {
    id: 'adv_07',
    roleId: 'advocate',
    name: 'Tree Census',
    description: 'Conduct a comprehensive census of trees in the park. Generates knowledge and builds the case for conservation.',
    flavorText: 'Each tree was tagged, measured, and given a name. You protect what you know.',
    baseValue: 2,
    cost: { volunteer: 1 },
    abilityCheck: { ability: 'technicalKnowledge', threshold: 9, skill: 'environmentalAssessment' },
    effects: [
      { type: 'add_resources', target: 'self', params: { resources: { knowledge: 2 } } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
    ],
    seriesPosition: 'middle',
    tags: ['ecological', 'assessment', 'community'],
    artworkId: 'art_adv_tree_census',
  },
  {
    id: 'adv_08',
    roleId: 'advocate',
    name: 'Media Campaign',
    description: 'Launch a media campaign that doubles CWS contribution for one zone this round. The spotlight is a powerful tool.',
    flavorText: 'The documentary aired at prime time. By morning, the park was trending.',
    baseValue: 4,
    cost: { influence: 2, knowledge: 1 },
    abilityCheck: { ability: 'communityTrust', threshold: 12, skill: 'publicSpeaking' },
    effects: [
      { type: 'add_progress_marker', target: 'zone', params: { count: 3, doubleCWSThisRound: true } },
      { type: 'grant_cp', target: 'self', params: { amount: 2 } },
    ],
    seriesPosition: 'middle',
    tags: ['community', 'ecological', 'communication'],
    artworkId: 'art_adv_media_campaign',
  },
  {
    id: 'adv_09',
    roleId: 'advocate',
    name: 'Legal Challenge',
    description: 'File a legal challenge against a non-compliant project or harmful action. The law is the ultimate equalizer.',
    flavorText: 'The court order arrived at 4 PM. Construction stopped at 4:01.',
    baseValue: 3,
    cost: { knowledge: 1, influence: 1 },
    abilityCheck: { ability: 'politicalLeverage', threshold: 12 },
    effects: [
      { type: 'block_action', target: 'zone', params: { blockNonCompliant: true } },
      { type: 'remove_problem_marker', target: 'zone', params: { count: 1 } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
    ],
    seriesPosition: 'closer',
    tags: ['governance', 'ecological', 'regulatory'],
    artworkId: 'art_adv_legal',
  },
  {
    id: 'adv_10',
    roleId: 'advocate',
    name: 'Community Health Assessment',
    description: 'Assess the health and social impact of park conditions on surrounding communities. Data drives action.',
    flavorText: 'The health survey revealed what everyone felt but nobody measured.',
    baseValue: 2,
    cost: { knowledge: 1 },
    abilityCheck: { ability: 'communityTrust', threshold: 10 },
    effects: [
      { type: 'reveal_zone_info', target: 'zone', params: { revealsSocialImpact: true, revealsHealth: true } },
      { type: 'add_resources', target: 'self', params: { resources: { influence: 1 } } },
    ],
    seriesPosition: 'middle',
    tags: ['community', 'assessment', 'ecological'],
    artworkId: 'art_adv_health',
  },
  {
    id: 'adv_11',
    roleId: 'advocate',
    name: 'Sustainability Framework',
    description: 'Establish a permanent sustainability framework for a zone. Provides ongoing ecological bonuses.',
    flavorText: 'Not a one-time fix but a forever commitment. Sustainability is a practice, not a project.',
    baseValue: 3,
    cost: { knowledge: 2, influence: 1 },
    abilityCheck: { ability: 'technicalKnowledge', threshold: 12, skill: 'environmentalAssessment' },
    effects: [
      { type: 'apply_status_effect', target: 'zone', params: { name: 'sustainability_framework', duration: 99, description: 'Permanent ecological protection and bonus' } },
      { type: 'grant_cp', target: 'self', params: { amount: 2 } },
      { type: 'add_progress_marker', target: 'zone', params: { count: 2 } },
    ],
    seriesPosition: 'closer',
    tags: ['ecological', 'design', 'governance'],
    artworkId: 'art_adv_sustainability',
  },
  {
    id: 'adv_12',
    roleId: 'advocate',
    name: 'Inclusive Design Petition',
    description: 'Petition to ensure all zone improvements meet accessibility and inclusion standards.',
    flavorText: 'A park for some is not a park at all. It must be for everyone.',
    baseValue: 2,
    cost: { influence: 1 },
    abilityCheck: { ability: 'communityTrust', threshold: 10, skill: 'publicSpeaking' },
    effects: [
      { type: 'force_agenda', target: 'zone', params: { accessibilityRequired: true } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
      { type: 'add_progress_marker', target: 'zone', params: { count: 1 } },
    ],
    seriesPosition: 'middle',
    tags: ['community', 'design', 'governance'],
    artworkId: 'art_adv_inclusive',
  },
  {
    id: 'adv_13',
    roleId: 'advocate',
    name: 'Indigenous Plant Restoration',
    description: 'Replace invasive species with indigenous plants. Restores ecological balance and educational value.',
    flavorText: 'The neem, tulsi, and jasmine returned. With them came the butterflies.',
    baseValue: 3,
    cost: { volunteer: 1, knowledge: 1 },
    abilityCheck: { ability: 'technicalKnowledge', threshold: 11, skill: 'environmentalAssessment' },
    effects: [
      { type: 'modify_zone_condition', target: 'zone', params: { improvement: 1, ecoZonesOnly: true } },
      { type: 'remove_problem_marker', target: 'zone', params: { count: 1 } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
    ],
    seriesPosition: 'closer',
    tags: ['ecological', 'construction', 'community'],
    artworkId: 'art_adv_indigenous',
  },
  {
    id: 'adv_14',
    roleId: 'advocate',
    name: 'Waste Management Plan',
    description: 'Develop and implement a comprehensive waste management strategy. Tackles both maintenance and ecological concerns.',
    flavorText: 'Segregate, reduce, recycle. Three words that could save the park.',
    baseValue: 3,
    cost: { knowledge: 1, volunteer: 1 },
    abilityCheck: { ability: 'technicalKnowledge', threshold: 10 },
    effects: [
      { type: 'remove_problem_marker', target: 'zone', params: { count: 1 } },
      { type: 'add_progress_marker', target: 'zone', params: { count: 2 } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
    ],
    seriesPosition: 'any',
    tags: ['ecological', 'maintenance', 'design'],
    artworkId: 'art_adv_waste',
  },
  {
    id: 'adv_15',
    roleId: 'advocate',
    name: 'Social Equity Report',
    description: 'Analyze how park benefits and burdens are distributed across different community groups.',
    flavorText: 'The numbers showed what intuition suggested: not everyone benefited equally.',
    baseValue: 2,
    cost: { knowledge: 1 },
    abilityCheck: { ability: 'communityTrust', threshold: 10 },
    effects: [
      { type: 'reveal_zone_info', target: 'all_zones', params: { revealsEquityDistribution: true } },
      { type: 'add_resources', target: 'self', params: { resources: { influence: 1, knowledge: 1 } } },
    ],
    seriesPosition: 'middle',
    tags: ['community', 'assessment', 'governance'],
    artworkId: 'art_adv_equity',
  },
  {
    id: 'adv_16',
    roleId: 'advocate',
    name: 'Watchdog Report',
    description: 'Publish an independent report on park management. Reveals hidden problems and holds authorities accountable.',
    flavorText: 'Transparency is the first step toward accountability.',
    baseValue: 2,
    cost: { knowledge: 1 },
    abilityCheck: { ability: 'communityTrust', threshold: 9 },
    effects: [
      { type: 'reveal_zone_info', target: 'zone', params: { revealsProblems: true, revealsManagement: true } },
      { type: 'modify_ability_temp', target: 'self', params: { ability: 'politicalLeverage', modifier: 2, duration: 1 } },
    ],
    seriesPosition: 'starter',
    tags: ['assessment', 'ecological', 'governance'],
    artworkId: 'art_adv_watchdog',
  },
];
