import { ActionCard } from '../models/types';

export const CITIZEN_CARDS: ActionCard[] = [
  {
    id: 'cit_01',
    roleId: 'citizen',
    name: 'Community Petition',
    description: 'Gather signatures and force an issue onto the public agenda. The voice of the people cannot be ignored.',
    flavorText: 'Five hundred signatures in three days. The message was clear.',
    baseValue: 3,
    cost: { volunteer: 1 },
    abilityCheck: { ability: 'communityTrust', threshold: 10, skill: 'publicSpeaking' },
    effects: [
      { type: 'force_agenda', target: 'zone', params: { priority: true } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
      { type: 'modify_ability_temp', target: 'self', params: { ability: 'politicalLeverage', modifier: 2, duration: 1 } },
    ],
    seriesPosition: 'starter',
    tags: ['community', 'negotiation', 'governance'],
    artworkId: 'art_cit_petition',
  },
  {
    id: 'cit_02',
    roleId: 'citizen',
    name: 'Volunteer Drive',
    description: 'Mobilize community members to donate their time. A powerful resource when budgets are tight.',
    flavorText: 'They came with gloves, brooms, and the kind of energy that money cannot buy.',
    baseValue: 2,
    cost: { influence: 1 },
    abilityCheck: null,
    effects: [
      { type: 'generate_volunteers', target: 'self', params: { count: 3 } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
    ],
    seriesPosition: 'any',
    tags: ['community', 'maintenance', 'coalition'],
    artworkId: 'art_cit_volunteer_drive',
  },
  {
    id: 'cit_03',
    roleId: 'citizen',
    name: 'Public Feedback',
    description: 'Collect and present community feedback on a zone or project. Reveals what people really think.',
    flavorText: 'The suggestion box overflowed. Each note was a story.',
    baseValue: 2,
    cost: { volunteer: 1 },
    abilityCheck: { ability: 'communityTrust', threshold: 9 },
    effects: [
      { type: 'reveal_zone_info', target: 'zone', params: { revealsSatisfaction: true, revealsNeeds: true } },
      { type: 'add_resources', target: 'self', params: { resources: { knowledge: 1 } } },
    ],
    seriesPosition: 'middle',
    tags: ['community', 'assessment', 'communication'],
    artworkId: 'art_cit_feedback',
  },
  {
    id: 'cit_04',
    roleId: 'citizen',
    name: 'Grassroots Campaign',
    description: 'Launch a sustained community campaign to build support and trust. Takes effort but yields lasting results.',
    flavorText: 'Door to door, street to street, the campaign grew like roots through soil.',
    baseValue: 3,
    cost: { volunteer: 2 },
    abilityCheck: { ability: 'communityTrust', threshold: 11, skill: 'publicSpeaking' },
    effects: [
      { type: 'modify_ability_temp', target: 'self', params: { ability: 'communityTrust', modifier: 3, duration: 2 } },
      { type: 'grant_cp', target: 'self', params: { amount: 2 } },
    ],
    seriesPosition: 'middle',
    tags: ['community', 'negotiation', 'coalition'],
    artworkId: 'art_cit_grassroots',
  },
  {
    id: 'cit_05',
    roleId: 'citizen',
    name: 'Neighborhood Watch',
    description: 'Organize community members to patrol and protect a zone. Resolves social problems and improves safety.',
    flavorText: 'Watchful eyes and walkie-talkies. The park felt safer already.',
    baseValue: 3,
    cost: { volunteer: 2 },
    abilityCheck: { ability: 'communityTrust', threshold: 11, skill: 'crisisManagement' },
    effects: [
      { type: 'remove_problem_marker', target: 'zone', params: { count: 2, socialOnly: true } },
      { type: 'add_progress_marker', target: 'zone', params: { count: 1 } },
    ],
    seriesPosition: 'closer',
    tags: ['community', 'maintenance', 'assessment'],
    artworkId: 'art_cit_neighborhood_watch',
  },
  {
    id: 'cit_06',
    roleId: 'citizen',
    name: 'Clean-Up Drive',
    description: 'Organize a community clean-up event. Direct action that improves zone condition immediately.',
    flavorText: 'Fifty bags of trash later, the park looked like it had taken a deep breath.',
    baseValue: 3,
    cost: { volunteer: 2 },
    abilityCheck: null,
    effects: [
      { type: 'modify_zone_condition', target: 'zone', params: { improvement: 1 } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
    ],
    seriesPosition: 'any',
    tags: ['maintenance', 'community', 'ecological'],
    artworkId: 'art_cit_cleanup',
  },
  {
    id: 'cit_07',
    roleId: 'citizen',
    name: 'Youth Engagement Program',
    description: 'Involve young people in park activities and improvement projects. Builds future community leaders.',
    flavorText: 'The teenagers who once vandalized the benches were now painting them.',
    baseValue: 3,
    cost: { volunteer: 1, knowledge: 1 },
    abilityCheck: { ability: 'communityTrust', threshold: 10 },
    effects: [
      { type: 'generate_volunteers', target: 'self', params: { count: 2 } },
      { type: 'add_resources', target: 'self', params: { resources: { knowledge: 1 } } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
    ],
    seriesPosition: 'middle',
    tags: ['community', 'ecological', 'design'],
    artworkId: 'art_cit_youth',
  },
  {
    id: 'cit_08',
    roleId: 'citizen',
    name: 'Elder Council Wisdom',
    description: 'Consult with long-time residents who remember the park in its prime. Their memories hold valuable insights.',
    flavorText: 'Grandmother Lakshmi remembered when the fountain still sang.',
    baseValue: 2,
    cost: { volunteer: 1 },
    abilityCheck: { ability: 'communityTrust', threshold: 9, skill: 'negotiation' },
    effects: [
      { type: 'modify_ability_temp', target: 'self', params: { ability: 'communityTrust', modifier: 2, duration: 1 } },
      { type: 'add_resources', target: 'self', params: { resources: { knowledge: 1, influence: 1 } } },
    ],
    seriesPosition: 'middle',
    tags: ['community', 'negotiation', 'assessment'],
    artworkId: 'art_cit_elder_council',
  },
  {
    id: 'cit_09',
    roleId: 'citizen',
    name: 'Cultural Event Proposal',
    description: 'Propose a cultural event that brings life and attention to a zone. Festivals transform spaces.',
    flavorText: 'The proposal promised music, food, and laughter. The committee could not say no.',
    baseValue: 3,
    cost: { volunteer: 1, influence: 1 },
    abilityCheck: { ability: 'communityTrust', threshold: 10, skill: 'publicSpeaking' },
    effects: [
      { type: 'add_progress_marker', target: 'zone', params: { count: 2 } },
      { type: 'grant_cp', target: 'all_players', params: { amount: 1 } },
    ],
    seriesPosition: 'starter',
    tags: ['community', 'commercial', 'design'],
    artworkId: 'art_cit_cultural_event',
  },
  {
    id: 'cit_10',
    roleId: 'citizen',
    name: 'Safety Complaint',
    description: 'File a formal safety complaint that forces authorities to respond. Sometimes you have to make noise.',
    flavorText: 'The letter was blunt: Fix it, or we go to the press.',
    baseValue: 2,
    cost: { influence: 1 },
    abilityCheck: { ability: 'communityTrust', threshold: 10 },
    effects: [
      { type: 'force_agenda', target: 'zone', params: { maintenancePriority: true } },
      { type: 'remove_problem_marker', target: 'zone', params: { count: 1 } },
    ],
    seriesPosition: 'middle',
    tags: ['community', 'maintenance', 'governance'],
    artworkId: 'art_cit_safety_complaint',
  },
  {
    id: 'cit_11',
    roleId: 'citizen',
    name: 'Parent Network',
    description: 'Activate the parent community to volunteer for playground improvements. Parents protect what their children use.',
    flavorText: 'When it comes to their children, parents move mountains.',
    baseValue: 2,
    cost: { volunteer: 1 },
    abilityCheck: null,
    effects: [
      { type: 'generate_volunteers', target: 'zone', params: { count: 2, playgroundBonus: true } },
      { type: 'add_progress_marker', target: 'zone', params: { count: 1 } },
    ],
    seriesPosition: 'middle',
    tags: ['community', 'maintenance', 'construction'],
    artworkId: 'art_cit_parent_network',
  },
  {
    id: 'cit_12',
    roleId: 'citizen',
    name: 'Morning Walker Alliance',
    description: 'Unite the dedicated morning walkers who know every crack and puddle on the walking track.',
    flavorText: 'At 5:30 AM, the track belongs to them. And they intend to keep it that way.',
    baseValue: 2,
    cost: { volunteer: 1 },
    abilityCheck: null,
    effects: [
      { type: 'add_progress_marker', target: 'zone', params: { count: 2, walkingTrackBonus: true } },
      { type: 'generate_volunteers', target: 'self', params: { count: 1 } },
    ],
    seriesPosition: 'any',
    tags: ['community', 'maintenance', 'ecological'],
    artworkId: 'art_cit_morning_walker',
  },
  {
    id: 'cit_13',
    roleId: 'citizen',
    name: 'Study Group Mobilization',
    description: 'Organize student volunteers from nearby colleges to help with park projects. Knowledge meets labor.',
    flavorText: 'The university students brought fresh ideas and tireless energy.',
    baseValue: 3,
    cost: { volunteer: 1, knowledge: 1 },
    abilityCheck: { ability: 'communityTrust', threshold: 10 },
    effects: [
      { type: 'generate_volunteers', target: 'self', params: { count: 2 } },
      { type: 'add_progress_marker', target: 'zone', params: { count: 2, openLawnBonus: true } },
    ],
    seriesPosition: 'middle',
    tags: ['community', 'ecological', 'assessment'],
    artworkId: 'art_cit_study_group',
  },
  {
    id: 'cit_14',
    roleId: 'citizen',
    name: 'Door-to-Door Survey',
    description: 'Conduct a neighborhood survey to gather data on park usage and needs. Information is power.',
    flavorText: 'Every doorbell rang with the same question: What does this park mean to you?',
    baseValue: 2,
    cost: { volunteer: 1 },
    abilityCheck: { ability: 'communityTrust', threshold: 9 },
    effects: [
      { type: 'reveal_zone_info', target: 'all_zones', params: { revealsUsage: true } },
      { type: 'add_resources', target: 'self', params: { resources: { knowledge: 1, influence: 1 } } },
    ],
    seriesPosition: 'starter',
    tags: ['assessment', 'community', 'communication'],
    artworkId: 'art_cit_survey',
  },
  {
    id: 'cit_15',
    roleId: 'citizen',
    name: 'Community Cookbook Fundraiser',
    description: 'Publish and sell a community cookbook to raise funds. Small budget but big community spirit.',
    flavorText: 'Grandmother\'s samosa recipe raised more money than the bake sale.',
    baseValue: 2,
    cost: { volunteer: 2 },
    abilityCheck: { ability: 'communityTrust', threshold: 10 },
    effects: [
      { type: 'add_resources', target: 'self', params: { resources: { budget: 3 } } },
      { type: 'grant_cp', target: 'self', params: { amount: 1 } },
    ],
    seriesPosition: 'closer',
    tags: ['community', 'funding', 'commercial'],
    artworkId: 'art_cit_cookbook',
  },
  {
    id: 'cit_16',
    roleId: 'citizen',
    name: 'Protest March',
    description: 'Organize a public protest demanding immediate action. High impact but may strain relationships.',
    flavorText: 'The chanting echoed off the buildings. The city could no longer pretend not to hear.',
    baseValue: 4,
    cost: { volunteer: 2, influence: 1 },
    abilityCheck: { ability: 'communityTrust', threshold: 12, skill: 'publicSpeaking' },
    effects: [
      { type: 'force_agenda', target: 'zone', params: { priority: true, immediate: true } },
      { type: 'add_progress_marker', target: 'zone', params: { count: 3 } },
      { type: 'modify_ability_temp', target: 'self', params: { ability: 'communityTrust', modifier: -1, duration: 1 } },
    ],
    seriesPosition: 'closer',
    tags: ['community', 'governance', 'negotiation'],
    artworkId: 'art_cit_protest',
  },
];
