import { ChallengeCard } from '../models/types';

// 10 site-specific challenges from the spec
export const SITE_CHALLENGES: ChallengeCard[] = [
  {
    id: 'ch_site_01',
    name: 'Algae Bloom Crisis',
    description: 'Toxic algae bloom threatens the boating pond ecosystem. Immediate intervention required to prevent fish kills and health hazards.',
    flavorText: 'The water turned green overnight. By morning, the fish were floating.',
    affectedZoneIds: ['boating_pond'],
    difficulty: 14,
    requirements: {
      minSeriesLength: 3,
      minUniqueRoles: 2,
      resourceCost: { budget: 3, knowledge: 2, volunteer: 2 },
      abilityChecks: [
        { ability: 'technicalKnowledge', threshold: 12, skill: 'environmentalAssessment' },
      ],
    },
    failureConsequences: [
      { type: 'zone_degrade', params: { zoneId: 'boating_pond', levels: 1 } },
      { type: 'cws_penalty', params: { amount: 3 } },
      { type: 'new_problem', params: { zoneId: 'boating_pond', problem: 'fish_kill' } },
    ],
    successRewards: [
      { type: 'zone_improve', params: { zoneId: 'boating_pond', levels: 2 } },
      { type: 'cws_bonus', params: { amount: 4 } },
      { type: 'remove_problem', params: { zoneId: 'boating_pond', problem: 'algae_bloom' } },
      { type: 'cp_bonus', params: { amount: 3 } },
    ],
    escalationPerRound: 2,
    roundsActive: 0,
    category: 'ecological',
    artworkId: 'art_ch_algae_bloom',
  },
  {
    id: 'ch_site_02',
    name: 'Playground Safety Hazard',
    description: 'A child was injured on rusted playground equipment. Parents demand immediate action or they will go to the media.',
    flavorText: 'The swing broke mid-air. Luckily, the sand was soft. Next time, it might not be.',
    affectedZoneIds: ['playground'],
    difficulty: 12,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 2,
      resourceCost: { budget: 3, material: 2 },
      abilityChecks: [
        { ability: 'authority', threshold: 10 },
      ],
    },
    failureConsequences: [
      { type: 'lock_zone', params: { zoneId: 'playground', duration: 2 } },
      { type: 'cws_penalty', params: { amount: 2 } },
      { type: 'status_effect', params: { target: 'administrator', effect: 'public_outrage', duration: 2 } },
    ],
    successRewards: [
      { type: 'zone_improve', params: { zoneId: 'playground', levels: 1 } },
      { type: 'remove_problem', params: { zoneId: 'playground', problem: 'playground_safety' } },
      { type: 'cws_bonus', params: { amount: 3 } },
      { type: 'cp_bonus', params: { amount: 2 } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'safety',
    artworkId: 'art_ch_playground_safety',
  },
  {
    id: 'ch_site_03',
    name: 'Vendor Encroachment Dispute',
    description: 'Unlicensed vendors have taken over walkways near the main entrance. Legal and community tensions are rising.',
    flavorText: 'The cart was in the way. The vendor would not move. The queue grew longer.',
    affectedZoneIds: ['main_entrance', 'vendor_hub'],
    difficulty: 11,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 2,
      resourceCost: { budget: 2, influence: 2 },
      abilityChecks: [
        { ability: 'authority', threshold: 11, skill: 'regulatoryNavigation' },
        { ability: 'communityTrust', threshold: 10, skill: 'negotiation' },
      ],
    },
    failureConsequences: [
      { type: 'zone_degrade', params: { zoneId: 'main_entrance', levels: 1 } },
      { type: 'cws_penalty', params: { amount: 2 } },
      { type: 'new_problem', params: { zoneId: 'vendor_hub', problem: 'vendor_overflow' } },
    ],
    successRewards: [
      { type: 'zone_improve', params: { zoneId: 'main_entrance', levels: 1 } },
      { type: 'remove_problem', params: { zoneId: 'main_entrance', problem: 'vendor_encroachment' } },
      { type: 'resource_gain', params: { resources: { budget: 2 } } },
      { type: 'cp_bonus', params: { amount: 2 } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'commercial',
    artworkId: 'art_ch_vendor_encroachment',
  },
  {
    id: 'ch_site_04',
    name: 'Fountain Restoration Project',
    description: 'The iconic fountain has been broken for years. A restoration project could become a symbol of renewal.',
    flavorText: 'Water had not danced here in a decade. The silence was deafening.',
    affectedZoneIds: ['fountain_plaza'],
    difficulty: 13,
    requirements: {
      minSeriesLength: 3,
      minUniqueRoles: 2,
      resourceCost: { budget: 4, material: 3, knowledge: 1 },
      abilityChecks: [
        { ability: 'technicalKnowledge', threshold: 12, skill: 'designThinking' },
      ],
    },
    failureConsequences: [
      { type: 'cws_penalty', params: { amount: 1 } },
      { type: 'resource_loss', params: { resources: { budget: 2 } } },
    ],
    successRewards: [
      { type: 'zone_improve', params: { zoneId: 'fountain_plaza', levels: 2 } },
      { type: 'remove_problem', params: { zoneId: 'fountain_plaza', problem: 'fountain_failure' } },
      { type: 'cws_bonus', params: { amount: 5 } },
      { type: 'cp_bonus', params: { amount: 3 } },
    ],
    escalationPerRound: 0,
    roundsActive: 0,
    category: 'infrastructure',
    artworkId: 'art_ch_fountain',
  },
  {
    id: 'ch_site_05',
    name: 'Restroom Block Overhaul',
    description: 'The restroom facilities are in deplorable condition. Visitor complaints have reached critical mass.',
    flavorText: 'The sign on the door said "Out of Order." It had been there for six months.',
    affectedZoneIds: ['restroom_block'],
    difficulty: 11,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 1,
      resourceCost: { budget: 3, material: 3 },
      abilityChecks: [
        { ability: 'resourcefulness', threshold: 10 },
      ],
    },
    failureConsequences: [
      { type: 'zone_degrade', params: { zoneId: 'restroom_block', levels: 1 } },
      { type: 'cws_penalty', params: { amount: 2 } },
    ],
    successRewards: [
      { type: 'zone_improve', params: { zoneId: 'restroom_block', levels: 2 } },
      { type: 'remove_problem', params: { zoneId: 'restroom_block', problem: 'restroom_failure' } },
      { type: 'cws_bonus', params: { amount: 3 } },
      { type: 'cp_bonus', params: { amount: 2 } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'infrastructure',
    artworkId: 'art_ch_restroom',
  },
  {
    id: 'ch_site_06',
    name: 'PPP Zone Deadlock',
    description: 'The public-private partnership development has stalled due to regulatory disputes and conflicting interests.',
    flavorText: 'Three parties. Three visions. Zero progress.',
    affectedZoneIds: ['ppp_zone'],
    difficulty: 14,
    requirements: {
      minSeriesLength: 3,
      minUniqueRoles: 3,
      resourceCost: { budget: 4, influence: 2, knowledge: 1 },
      abilityChecks: [
        { ability: 'politicalLeverage', threshold: 12, skill: 'coalitionBuilding' },
        { ability: 'resourcefulness', threshold: 11 },
      ],
    },
    failureConsequences: [
      { type: 'cws_penalty', params: { amount: 2 } },
      { type: 'new_problem', params: { zoneId: 'ppp_zone', problem: 'legal_dispute' } },
      { type: 'resource_loss', params: { resources: { budget: 2, influence: 1 } } },
    ],
    successRewards: [
      { type: 'zone_improve', params: { zoneId: 'ppp_zone', levels: 2 } },
      { type: 'remove_problem', params: { zoneId: 'ppp_zone', problem: 'stalled_development' } },
      { type: 'cws_bonus', params: { amount: 5 } },
      { type: 'cp_bonus', params: { amount: 4 } },
      { type: 'resource_gain', params: { resources: { budget: 3 } } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'political',
    artworkId: 'art_ch_ppp_deadlock',
  },
  {
    id: 'ch_site_07',
    name: 'Broken Footpaths Emergency',
    description: 'An elderly walker tripped on a broken footpath. The walking track needs urgent repairs before more injuries occur.',
    flavorText: 'The crack had been reported three times. This time, someone fell.',
    affectedZoneIds: ['walking_track'],
    difficulty: 10,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 1,
      resourceCost: { budget: 2, material: 2 },
      abilityChecks: [
        { ability: 'resourcefulness', threshold: 9 },
      ],
    },
    failureConsequences: [
      { type: 'zone_degrade', params: { zoneId: 'walking_track', levels: 1 } },
      { type: 'cws_penalty', params: { amount: 1 } },
      { type: 'new_problem', params: { zoneId: 'walking_track', problem: 'injury_liability' } },
    ],
    successRewards: [
      { type: 'zone_improve', params: { zoneId: 'walking_track', levels: 1 } },
      { type: 'remove_problem', params: { zoneId: 'walking_track', problem: 'broken_footpaths' } },
      { type: 'cws_bonus', params: { amount: 2 } },
      { type: 'cp_bonus', params: { amount: 2 } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'safety',
    artworkId: 'art_ch_footpaths',
  },
  {
    id: 'ch_site_08',
    name: 'Maintenance Staff Shortage',
    description: 'The maintenance depot is critically understaffed. Park upkeep is falling behind across all zones.',
    flavorText: 'One gardener for fourteen zones. The weeds were winning.',
    affectedZoneIds: ['maintenance_depot'],
    difficulty: 12,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 2,
      resourceCost: { budget: 3, volunteer: 2 },
      abilityChecks: [
        { ability: 'authority', threshold: 10, skill: 'budgeting' },
      ],
    },
    failureConsequences: [
      { type: 'zone_degrade', params: { zoneId: 'maintenance_depot', levels: 1 } },
      { type: 'cws_penalty', params: { amount: 3 } },
      { type: 'difficulty_increase', params: { amount: 1, scope: 'all' } },
    ],
    successRewards: [
      { type: 'zone_improve', params: { zoneId: 'maintenance_depot', levels: 1 } },
      { type: 'remove_problem', params: { zoneId: 'maintenance_depot', problem: 'understaffed' } },
      { type: 'cws_bonus', params: { amount: 3 } },
      { type: 'cp_bonus', params: { amount: 2 } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'maintenance',
    artworkId: 'art_ch_staff_shortage',
  },
  {
    id: 'ch_site_09',
    name: 'Irrigation System Collapse',
    description: 'The herbal garden irrigation system has failed completely. Without water, rare medicinal plants will die within days.',
    flavorText: 'The pipes crumbled like old bones. The garden held its breath.',
    affectedZoneIds: ['herbal_garden'],
    difficulty: 11,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 1,
      resourceCost: { budget: 2, material: 2, knowledge: 1 },
      abilityChecks: [
        { ability: 'technicalKnowledge', threshold: 10 },
      ],
    },
    failureConsequences: [
      { type: 'zone_degrade', params: { zoneId: 'herbal_garden', levels: 2 } },
      { type: 'cws_penalty', params: { amount: 2 } },
    ],
    successRewards: [
      { type: 'zone_improve', params: { zoneId: 'herbal_garden', levels: 1 } },
      { type: 'remove_problem', params: { zoneId: 'herbal_garden', problem: 'irrigation_failure' } },
      { type: 'cws_bonus', params: { amount: 3 } },
      { type: 'cp_bonus', params: { amount: 2 } },
    ],
    escalationPerRound: 2,
    roundsActive: 0,
    category: 'infrastructure',
    artworkId: 'art_ch_irrigation',
  },
  {
    id: 'ch_site_10',
    name: 'LED Installation Failure',
    description: 'Multiple LED panels along Fiber Optic Lane have failed. The evening attraction is dark and safety is compromised.',
    flavorText: 'The lane that once glowed like a runway now swallowed the darkness whole.',
    affectedZoneIds: ['fiber_optic_lane'],
    difficulty: 10,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 1,
      resourceCost: { budget: 2, material: 2 },
      abilityChecks: [
        { ability: 'technicalKnowledge', threshold: 10 },
      ],
    },
    failureConsequences: [
      { type: 'zone_degrade', params: { zoneId: 'fiber_optic_lane', levels: 1 } },
      { type: 'cws_penalty', params: { amount: 1 } },
      { type: 'new_problem', params: { zoneId: 'fiber_optic_lane', problem: 'safety_hazard_dark' } },
    ],
    successRewards: [
      { type: 'zone_improve', params: { zoneId: 'fiber_optic_lane', levels: 1 } },
      { type: 'remove_problem', params: { zoneId: 'fiber_optic_lane', problem: 'led_failures' } },
      { type: 'cws_bonus', params: { amount: 2 } },
      { type: 'cp_bonus', params: { amount: 2 } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'infrastructure',
    artworkId: 'art_ch_led',
  },
];

// 30 generic challenges
export const GENERIC_CHALLENGES: ChallengeCard[] = [
  {
    id: 'ch_gen_01',
    name: 'Budget Crisis',
    description: 'Municipal budget cuts threaten to reduce park funding by 50%. Immediate advocacy and alternative funding needed.',
    flavorText: 'The treasury letter was terse: Tighten your belts or lose your park.',
    affectedZoneIds: [],
    difficulty: 13,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 2,
      resourceCost: { budget: 3, influence: 2 },
      abilityChecks: [
        { ability: 'politicalLeverage', threshold: 12, skill: 'budgeting' },
      ],
    },
    failureConsequences: [
      { type: 'resource_loss', params: { resources: { budget: 3 }, target: 'all_players' } },
      { type: 'cws_penalty', params: { amount: 3 } },
    ],
    successRewards: [
      { type: 'resource_gain', params: { resources: { budget: 2 } } },
      { type: 'cws_bonus', params: { amount: 2 } },
      { type: 'cp_bonus', params: { amount: 2 } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'political',
    artworkId: 'art_ch_budget_crisis',
  },
  {
    id: 'ch_gen_02',
    name: 'Political Interference',
    description: 'A local politician wants to rename and rebrand the park for electoral benefit. The changes would disrupt ongoing projects.',
    flavorText: 'The banner was already printed. The election was in three weeks.',
    affectedZoneIds: [],
    difficulty: 12,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 2,
      resourceCost: { influence: 3 },
      abilityChecks: [
        { ability: 'politicalLeverage', threshold: 12, skill: 'coalitionBuilding' },
      ],
    },
    failureConsequences: [
      { type: 'cws_penalty', params: { amount: 2 } },
      { type: 'status_effect', params: { target: 'all', effect: 'political_disruption', duration: 2 } },
    ],
    successRewards: [
      { type: 'cws_bonus', params: { amount: 2 } },
      { type: 'resource_gain', params: { resources: { influence: 2 } } },
      { type: 'cp_bonus', params: { amount: 2 } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'political',
    artworkId: 'art_ch_political',
  },
  {
    id: 'ch_gen_03',
    name: 'Monsoon Damage',
    description: 'Heavy monsoon rains have caused flooding and structural damage across multiple zones.',
    flavorText: 'The rain came in sheets. When it stopped, the park was unrecognizable.',
    affectedZoneIds: ['open_lawn', 'walking_track', 'boating_pond'],
    difficulty: 14,
    requirements: {
      minSeriesLength: 3,
      minUniqueRoles: 2,
      resourceCost: { budget: 4, material: 3, volunteer: 2 },
      abilityChecks: [
        { ability: 'adaptability', threshold: 12, skill: 'crisisManagement' },
      ],
    },
    failureConsequences: [
      { type: 'zone_degrade', params: { zoneId: 'open_lawn', levels: 1 } },
      { type: 'zone_degrade', params: { zoneId: 'walking_track', levels: 1 } },
      { type: 'cws_penalty', params: { amount: 4 } },
    ],
    successRewards: [
      { type: 'cws_bonus', params: { amount: 3 } },
      { type: 'cp_bonus', params: { amount: 3 } },
      { type: 'resource_gain', params: { resources: { material: 2 } } },
    ],
    escalationPerRound: 2,
    roundsActive: 0,
    category: 'infrastructure',
    artworkId: 'art_ch_monsoon',
  },
  {
    id: 'ch_gen_04',
    name: 'Community Protest',
    description: 'Residents are protesting the lack of improvements. They threaten to block park entrances until demands are met.',
    flavorText: 'The placards read: Our Park, Our Rights. The crowd grew by the hour.',
    affectedZoneIds: ['main_entrance'],
    difficulty: 11,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 2,
      resourceCost: { influence: 2, volunteer: 2 },
      abilityChecks: [
        { ability: 'communityTrust', threshold: 12, skill: 'negotiation' },
      ],
    },
    failureConsequences: [
      { type: 'lock_zone', params: { zoneId: 'main_entrance', duration: 1 } },
      { type: 'cws_penalty', params: { amount: 3 } },
      { type: 'status_effect', params: { target: 'administrator', effect: 'public_distrust', duration: 2 } },
    ],
    successRewards: [
      { type: 'cws_bonus', params: { amount: 3 } },
      { type: 'cp_bonus', params: { amount: 3 } },
      { type: 'resource_gain', params: { resources: { volunteer: 2 } } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'social',
    artworkId: 'art_ch_protest',
  },
  {
    id: 'ch_gen_05',
    name: 'Media Scandal',
    description: 'A news outlet has published an expos\u00e9 on park mismanagement. Damage control is urgent.',
    flavorText: 'The headline was brutal. The comment section was worse.',
    affectedZoneIds: [],
    difficulty: 12,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 2,
      resourceCost: { influence: 3, knowledge: 1 },
      abilityChecks: [
        { ability: 'politicalLeverage', threshold: 11 },
        { ability: 'communityTrust', threshold: 10 },
      ],
    },
    failureConsequences: [
      { type: 'cws_penalty', params: { amount: 4 } },
      { type: 'status_effect', params: { target: 'all', effect: 'media_scrutiny', duration: 2 } },
    ],
    successRewards: [
      { type: 'cws_bonus', params: { amount: 2 } },
      { type: 'resource_gain', params: { resources: { influence: 2 } } },
      { type: 'cp_bonus', params: { amount: 2 } },
    ],
    escalationPerRound: 2,
    roundsActive: 0,
    category: 'social',
    artworkId: 'art_ch_media_scandal',
  },
  {
    id: 'ch_gen_06',
    name: 'Ecological Disaster',
    description: 'Chemical runoff from a nearby factory has contaminated the boating pond and herbal garden soil.',
    flavorText: 'The chemical smell hit first. Then the dying plants. Then the panic.',
    affectedZoneIds: ['boating_pond', 'herbal_garden'],
    difficulty: 15,
    requirements: {
      minSeriesLength: 3,
      minUniqueRoles: 3,
      resourceCost: { budget: 4, knowledge: 3, volunteer: 2 },
      abilityChecks: [
        { ability: 'technicalKnowledge', threshold: 13, skill: 'environmentalAssessment' },
        { ability: 'authority', threshold: 11 },
      ],
    },
    failureConsequences: [
      { type: 'zone_degrade', params: { zoneId: 'boating_pond', levels: 1 } },
      { type: 'zone_degrade', params: { zoneId: 'herbal_garden', levels: 1 } },
      { type: 'cws_penalty', params: { amount: 5 } },
    ],
    successRewards: [
      { type: 'zone_improve', params: { zoneId: 'boating_pond', levels: 1 } },
      { type: 'zone_improve', params: { zoneId: 'herbal_garden', levels: 1 } },
      { type: 'cws_bonus', params: { amount: 5 } },
      { type: 'cp_bonus', params: { amount: 4 } },
    ],
    escalationPerRound: 2,
    roundsActive: 0,
    category: 'ecological',
    artworkId: 'art_ch_eco_disaster',
  },
  {
    id: 'ch_gen_07',
    name: 'Vendor Strike',
    description: 'Park vendors have gone on strike over licensing fees and operational restrictions.',
    flavorText: 'The shutters came down. The park felt emptier without the smell of chai.',
    affectedZoneIds: ['vendor_hub', 'main_entrance'],
    difficulty: 10,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 2,
      resourceCost: { budget: 2, influence: 1 },
      abilityChecks: [
        { ability: 'communityTrust', threshold: 10, skill: 'negotiation' },
      ],
    },
    failureConsequences: [
      { type: 'zone_degrade', params: { zoneId: 'vendor_hub', levels: 1 } },
      { type: 'cws_penalty', params: { amount: 2 } },
      { type: 'resource_loss', params: { resources: { budget: 2 } } },
    ],
    successRewards: [
      { type: 'zone_improve', params: { zoneId: 'vendor_hub', levels: 1 } },
      { type: 'cws_bonus', params: { amount: 2 } },
      { type: 'cp_bonus', params: { amount: 2 } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'commercial',
    artworkId: 'art_ch_vendor_strike',
  },
  {
    id: 'ch_gen_08',
    name: 'Safety Audit Failure',
    description: 'An external safety audit has found multiple violations. The park risks partial closure.',
    flavorText: 'The auditor shook his head slowly. The clipboard was covered in red marks.',
    affectedZoneIds: ['playground', 'exercise_zone', 'walking_track'],
    difficulty: 13,
    requirements: {
      minSeriesLength: 3,
      minUniqueRoles: 2,
      resourceCost: { budget: 3, material: 3, knowledge: 1 },
      abilityChecks: [
        { ability: 'authority', threshold: 11, skill: 'regulatoryNavigation' },
        { ability: 'technicalKnowledge', threshold: 10 },
      ],
    },
    failureConsequences: [
      { type: 'lock_zone', params: { zoneId: 'playground', duration: 2 } },
      { type: 'lock_zone', params: { zoneId: 'exercise_zone', duration: 1 } },
      { type: 'cws_penalty', params: { amount: 4 } },
    ],
    successRewards: [
      { type: 'zone_improve', params: { zoneId: 'playground', levels: 1 } },
      { type: 'zone_improve', params: { zoneId: 'exercise_zone', levels: 1 } },
      { type: 'cws_bonus', params: { amount: 3 } },
      { type: 'cp_bonus', params: { amount: 3 } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'safety',
    artworkId: 'art_ch_safety_audit',
  },
  {
    id: 'ch_gen_09',
    name: 'Accessibility Complaint',
    description: 'A disability rights organization has filed a formal complaint about park accessibility. Legal action is threatened.',
    flavorText: 'The wheelchair could not get past the second gate. The ramp was a myth.',
    affectedZoneIds: ['main_entrance', 'restroom_block'],
    difficulty: 11,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 2,
      resourceCost: { budget: 3, material: 2 },
      abilityChecks: [
        { ability: 'communityTrust', threshold: 10 },
        { ability: 'technicalKnowledge', threshold: 9 },
      ],
    },
    failureConsequences: [
      { type: 'cws_penalty', params: { amount: 3 } },
      { type: 'status_effect', params: { target: 'administrator', effect: 'legal_pressure', duration: 2 } },
    ],
    successRewards: [
      { type: 'zone_improve', params: { zoneId: 'main_entrance', levels: 1 } },
      { type: 'zone_improve', params: { zoneId: 'restroom_block', levels: 1 } },
      { type: 'cws_bonus', params: { amount: 3 } },
      { type: 'cp_bonus', params: { amount: 3 } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'social',
    artworkId: 'art_ch_accessibility',
  },
  {
    id: 'ch_gen_10',
    name: 'Heritage Violation',
    description: 'A development project has inadvertently damaged a heritage structure. Conservation authorities are investigating.',
    flavorText: 'The old wall crumbled under the excavator. A hundred years of history in a cloud of dust.',
    affectedZoneIds: ['sculpture_garden'],
    difficulty: 12,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 2,
      resourceCost: { knowledge: 2, influence: 2 },
      abilityChecks: [
        { ability: 'politicalLeverage', threshold: 11 },
        { ability: 'technicalKnowledge', threshold: 10 },
      ],
    },
    failureConsequences: [
      { type: 'zone_degrade', params: { zoneId: 'sculpture_garden', levels: 1 } },
      { type: 'cws_penalty', params: { amount: 3 } },
      { type: 'lock_zone', params: { zoneId: 'sculpture_garden', duration: 1 } },
    ],
    successRewards: [
      { type: 'zone_improve', params: { zoneId: 'sculpture_garden', levels: 1 } },
      { type: 'cws_bonus', params: { amount: 3 } },
      { type: 'cp_bonus', params: { amount: 2 } },
      { type: 'resource_gain', params: { resources: { knowledge: 2 } } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'social',
    artworkId: 'art_ch_heritage',
  },
  {
    id: 'ch_gen_11',
    name: 'Noise Complaint Escalation',
    description: 'Residents near the open lawn are complaining about excessive noise from events. Municipal notice served.',
    flavorText: 'The music was joyful. The neighbors were not.',
    affectedZoneIds: ['open_lawn'],
    difficulty: 9,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 2,
      resourceCost: { influence: 2 },
      abilityChecks: [
        { ability: 'communityTrust', threshold: 10, skill: 'negotiation' },
      ],
    },
    failureConsequences: [
      { type: 'cws_penalty', params: { amount: 1 } },
      { type: 'new_problem', params: { zoneId: 'open_lawn', problem: 'noise_restriction' } },
    ],
    successRewards: [
      { type: 'cws_bonus', params: { amount: 2 } },
      { type: 'cp_bonus', params: { amount: 2 } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'social',
    artworkId: 'art_ch_noise',
  },
  {
    id: 'ch_gen_12',
    name: 'Parking Chaos',
    description: 'Haphazard parking is blocking the main entrance and creating safety hazards. Traffic management needed.',
    flavorText: 'Cars parked on the footpath, on the grass, even blocking the fire lane.',
    affectedZoneIds: ['main_entrance'],
    difficulty: 10,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 1,
      resourceCost: { budget: 2, material: 1 },
      abilityChecks: [
        { ability: 'authority', threshold: 10, skill: 'regulatoryNavigation' },
      ],
    },
    failureConsequences: [
      { type: 'zone_degrade', params: { zoneId: 'main_entrance', levels: 1 } },
      { type: 'cws_penalty', params: { amount: 1 } },
    ],
    successRewards: [
      { type: 'zone_improve', params: { zoneId: 'main_entrance', levels: 1 } },
      { type: 'cws_bonus', params: { amount: 2 } },
      { type: 'cp_bonus', params: { amount: 1 } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'infrastructure',
    artworkId: 'art_ch_parking',
  },
  {
    id: 'ch_gen_13',
    name: 'Waste Management Failure',
    description: 'The waste collection system has broken down. Garbage is piling up across the park.',
    flavorText: 'The bins overflowed on Monday. By Friday, the smell had its own postal code.',
    affectedZoneIds: ['open_lawn', 'vendor_hub', 'playground'],
    difficulty: 11,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 1,
      resourceCost: { budget: 2, volunteer: 2 },
      abilityChecks: [
        { ability: 'resourcefulness', threshold: 10 },
      ],
    },
    failureConsequences: [
      { type: 'zone_degrade', params: { zoneId: 'open_lawn', levels: 1 } },
      { type: 'zone_degrade', params: { zoneId: 'vendor_hub', levels: 1 } },
      { type: 'cws_penalty', params: { amount: 3 } },
    ],
    successRewards: [
      { type: 'cws_bonus', params: { amount: 2 } },
      { type: 'cp_bonus', params: { amount: 2 } },
      { type: 'resource_gain', params: { resources: { volunteer: 1 } } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'maintenance',
    artworkId: 'art_ch_waste',
  },
  {
    id: 'ch_gen_14',
    name: 'Water Supply Cut',
    description: 'The municipal water supply to the park has been cut due to unpaid bills and infrastructure failure.',
    flavorText: 'No water for the gardens. No water for the restrooms. No water for the fountain that was just fixed.',
    affectedZoneIds: ['herbal_garden', 'restroom_block', 'fountain_plaza'],
    difficulty: 12,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 2,
      resourceCost: { budget: 3, influence: 1 },
      abilityChecks: [
        { ability: 'authority', threshold: 11, skill: 'regulatoryNavigation' },
      ],
    },
    failureConsequences: [
      { type: 'zone_degrade', params: { zoneId: 'herbal_garden', levels: 1 } },
      { type: 'zone_degrade', params: { zoneId: 'restroom_block', levels: 1 } },
      { type: 'cws_penalty', params: { amount: 3 } },
    ],
    successRewards: [
      { type: 'cws_bonus', params: { amount: 2 } },
      { type: 'cp_bonus', params: { amount: 2 } },
    ],
    escalationPerRound: 2,
    roundsActive: 0,
    category: 'infrastructure',
    artworkId: 'art_ch_water_cut',
  },
  {
    id: 'ch_gen_15',
    name: 'Electricity Outage',
    description: 'A power outage has knocked out lighting, security cameras, and the fiber optic lane installations.',
    flavorText: 'Darkness fell at 6 PM. The park became a different place entirely.',
    affectedZoneIds: ['fiber_optic_lane', 'main_entrance'],
    difficulty: 10,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 1,
      resourceCost: { budget: 2, material: 1 },
      abilityChecks: [
        { ability: 'resourcefulness', threshold: 10 },
      ],
    },
    failureConsequences: [
      { type: 'zone_degrade', params: { zoneId: 'fiber_optic_lane', levels: 1 } },
      { type: 'cws_penalty', params: { amount: 2 } },
      { type: 'new_problem', params: { zoneId: 'main_entrance', problem: 'security_risk' } },
    ],
    successRewards: [
      { type: 'zone_improve', params: { zoneId: 'fiber_optic_lane', levels: 1 } },
      { type: 'cws_bonus', params: { amount: 2 } },
      { type: 'cp_bonus', params: { amount: 1 } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'infrastructure',
    artworkId: 'art_ch_electricity',
  },
  {
    id: 'ch_gen_16',
    name: 'Staff Strike',
    description: 'Park maintenance and security staff have gone on strike over wages and working conditions.',
    flavorText: 'The gates remained locked. A handwritten sign: "No work without dignity."',
    affectedZoneIds: ['maintenance_depot'],
    difficulty: 12,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 2,
      resourceCost: { budget: 3, influence: 2 },
      abilityChecks: [
        { ability: 'communityTrust', threshold: 11, skill: 'negotiation' },
      ],
    },
    failureConsequences: [
      { type: 'cws_penalty', params: { amount: 3 } },
      { type: 'difficulty_increase', params: { amount: 2, scope: 'maintenance' } },
      { type: 'new_problem', params: { zoneId: 'maintenance_depot', problem: 'no_maintenance' } },
    ],
    successRewards: [
      { type: 'cws_bonus', params: { amount: 3 } },
      { type: 'cp_bonus', params: { amount: 2 } },
      { type: 'resource_gain', params: { resources: { volunteer: 2 } } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'social',
    artworkId: 'art_ch_staff_strike',
  },
  {
    id: 'ch_gen_17',
    name: 'Stray Animal Problem',
    description: 'A growing population of stray dogs in the park is causing safety concerns, especially near the playground.',
    flavorText: 'The dogs were not aggressive, but the fear was real.',
    affectedZoneIds: ['playground', 'walking_track'],
    difficulty: 9,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 1,
      resourceCost: { budget: 1, volunteer: 2 },
      abilityChecks: [
        { ability: 'communityTrust', threshold: 9, skill: 'crisisManagement' },
      ],
    },
    failureConsequences: [
      { type: 'cws_penalty', params: { amount: 1 } },
      { type: 'new_problem', params: { zoneId: 'playground', problem: 'stray_animals' } },
    ],
    successRewards: [
      { type: 'cws_bonus', params: { amount: 2 } },
      { type: 'cp_bonus', params: { amount: 1 } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'safety',
    artworkId: 'art_ch_stray_animals',
  },
  {
    id: 'ch_gen_18',
    name: 'Illegal Dumping',
    description: 'Construction waste is being illegally dumped near the park boundary, threatening soil and water quality.',
    flavorText: 'The dump trucks came at night. By dawn, a small hill of rubble had appeared.',
    affectedZoneIds: ['ppp_zone', 'maintenance_depot'],
    difficulty: 11,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 2,
      resourceCost: { budget: 2, influence: 1, volunteer: 1 },
      abilityChecks: [
        { ability: 'authority', threshold: 11, skill: 'regulatoryNavigation' },
      ],
    },
    failureConsequences: [
      { type: 'zone_degrade', params: { zoneId: 'ppp_zone', levels: 1 } },
      { type: 'cws_penalty', params: { amount: 2 } },
    ],
    successRewards: [
      { type: 'cws_bonus', params: { amount: 2 } },
      { type: 'cp_bonus', params: { amount: 2 } },
      { type: 'resource_gain', params: { resources: { material: 1 } } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'ecological',
    artworkId: 'art_ch_illegal_dumping',
  },
  {
    id: 'ch_gen_19',
    name: 'Vandalism Spree',
    description: 'A wave of vandalism has damaged benches, signs, and the sculpture garden installations.',
    flavorText: 'Spray paint on marble. Broken glass on pathways. Anger without an address.',
    affectedZoneIds: ['sculpture_garden', 'exercise_zone'],
    difficulty: 10,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 1,
      resourceCost: { budget: 2, material: 2 },
      abilityChecks: [
        { ability: 'communityTrust', threshold: 10 },
      ],
    },
    failureConsequences: [
      { type: 'zone_degrade', params: { zoneId: 'sculpture_garden', levels: 1 } },
      { type: 'cws_penalty', params: { amount: 2 } },
    ],
    successRewards: [
      { type: 'zone_improve', params: { zoneId: 'sculpture_garden', levels: 1 } },
      { type: 'cws_bonus', params: { amount: 2 } },
      { type: 'cp_bonus', params: { amount: 1 } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'social',
    artworkId: 'art_ch_vandalism',
  },
  {
    id: 'ch_gen_20',
    name: 'Invasive Species Outbreak',
    description: 'An invasive plant species is spreading rapidly through the herbal garden and open lawn areas.',
    flavorText: 'The vine grew an inch a day. Soon, it would be the only green thing left.',
    affectedZoneIds: ['herbal_garden', 'open_lawn'],
    difficulty: 11,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 1,
      resourceCost: { knowledge: 2, volunteer: 2 },
      abilityChecks: [
        { ability: 'technicalKnowledge', threshold: 11, skill: 'environmentalAssessment' },
      ],
    },
    failureConsequences: [
      { type: 'zone_degrade', params: { zoneId: 'herbal_garden', levels: 1 } },
      { type: 'cws_penalty', params: { amount: 2 } },
    ],
    successRewards: [
      { type: 'zone_improve', params: { zoneId: 'herbal_garden', levels: 1 } },
      { type: 'cws_bonus', params: { amount: 2 } },
      { type: 'cp_bonus', params: { amount: 2 } },
      { type: 'resource_gain', params: { resources: { knowledge: 1 } } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'ecological',
    artworkId: 'art_ch_invasive',
  },
  {
    id: 'ch_gen_21',
    name: 'Heat Wave Emergency',
    description: 'An extreme heat wave is stressing park vegetation and making outdoor activities dangerous.',
    flavorText: 'The thermometer read 47 degrees. The grass turned brown. The benches burned to touch.',
    affectedZoneIds: ['open_lawn', 'exercise_zone', 'walking_track'],
    difficulty: 12,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 2,
      resourceCost: { budget: 2, volunteer: 2, material: 1 },
      abilityChecks: [
        { ability: 'adaptability', threshold: 11, skill: 'crisisManagement' },
      ],
    },
    failureConsequences: [
      { type: 'zone_degrade', params: { zoneId: 'open_lawn', levels: 1 } },
      { type: 'cws_penalty', params: { amount: 2 } },
    ],
    successRewards: [
      { type: 'cws_bonus', params: { amount: 2 } },
      { type: 'cp_bonus', params: { amount: 2 } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'ecological',
    artworkId: 'art_ch_heat_wave',
  },
  {
    id: 'ch_gen_22',
    name: 'Funding Embezzlement Suspicion',
    description: 'Rumors of fund misuse surface. An audit is demanded by citizens and the media.',
    flavorText: 'The accounts did not add up. Someone had some explaining to do.',
    affectedZoneIds: [],
    difficulty: 13,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 2,
      resourceCost: { knowledge: 2, influence: 2 },
      abilityChecks: [
        { ability: 'authority', threshold: 12, skill: 'budgeting' },
        { ability: 'communityTrust', threshold: 10 },
      ],
    },
    failureConsequences: [
      { type: 'cws_penalty', params: { amount: 4 } },
      { type: 'resource_loss', params: { resources: { budget: 3 } } },
      { type: 'status_effect', params: { target: 'administrator', effect: 'corruption_suspicion', duration: 3 } },
    ],
    successRewards: [
      { type: 'cws_bonus', params: { amount: 2 } },
      { type: 'cp_bonus', params: { amount: 3 } },
      { type: 'resource_gain', params: { resources: { influence: 2 } } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'political',
    artworkId: 'art_ch_embezzlement',
  },
  {
    id: 'ch_gen_23',
    name: 'Mosquito Menace',
    description: 'Stagnant water in the boating pond and poor zones has led to a mosquito breeding epidemic. Health risk rising.',
    flavorText: 'The buzz was constant. The bites were worse. The dengue cases were alarming.',
    affectedZoneIds: ['boating_pond', 'restroom_block'],
    difficulty: 10,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 1,
      resourceCost: { budget: 2, volunteer: 1 },
      abilityChecks: [
        { ability: 'technicalKnowledge', threshold: 9 },
      ],
    },
    failureConsequences: [
      { type: 'cws_penalty', params: { amount: 2 } },
      { type: 'new_problem', params: { zoneId: 'boating_pond', problem: 'health_hazard' } },
    ],
    successRewards: [
      { type: 'cws_bonus', params: { amount: 2 } },
      { type: 'cp_bonus', params: { amount: 1 } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'ecological',
    artworkId: 'art_ch_mosquito',
  },
  {
    id: 'ch_gen_24',
    name: 'Contractor Default',
    description: 'A contracted construction firm has abandoned a project mid-way, leaving an unsafe work site.',
    flavorText: 'The scaffolding stood empty. The workers vanished. The deposit vanished with them.',
    affectedZoneIds: ['ppp_zone'],
    difficulty: 12,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 2,
      resourceCost: { budget: 3, material: 2 },
      abilityChecks: [
        { ability: 'resourcefulness', threshold: 11, skill: 'budgeting' },
      ],
    },
    failureConsequences: [
      { type: 'zone_degrade', params: { zoneId: 'ppp_zone', levels: 1 } },
      { type: 'cws_penalty', params: { amount: 2 } },
      { type: 'resource_loss', params: { resources: { budget: 2 } } },
    ],
    successRewards: [
      { type: 'zone_improve', params: { zoneId: 'ppp_zone', levels: 1 } },
      { type: 'cws_bonus', params: { amount: 2 } },
      { type: 'cp_bonus', params: { amount: 2 } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'infrastructure',
    artworkId: 'art_ch_contractor',
  },
  {
    id: 'ch_gen_25',
    name: 'Tree Fall Emergency',
    description: 'A large old tree has fallen during a storm, blocking the walking track and damaging a bench.',
    flavorText: 'The banyan had stood for sixty years. It fell in sixty seconds.',
    affectedZoneIds: ['walking_track', 'open_lawn'],
    difficulty: 8,
    requirements: {
      minSeriesLength: 1,
      minUniqueRoles: 1,
      resourceCost: { material: 2, volunteer: 1 },
      abilityChecks: [
        { ability: 'adaptability', threshold: 9, skill: 'crisisManagement' },
      ],
    },
    failureConsequences: [
      { type: 'lock_zone', params: { zoneId: 'walking_track', duration: 1 } },
      { type: 'cws_penalty', params: { amount: 1 } },
    ],
    successRewards: [
      { type: 'cws_bonus', params: { amount: 1 } },
      { type: 'cp_bonus', params: { amount: 1 } },
      { type: 'resource_gain', params: { resources: { material: 1 } } },
    ],
    escalationPerRound: 0,
    roundsActive: 0,
    category: 'maintenance',
    artworkId: 'art_ch_tree_fall',
  },
  {
    id: 'ch_gen_26',
    name: 'Event Permit Dispute',
    description: 'A large commercial event has been scheduled without proper community consultation. Residents are angry.',
    flavorText: 'The stage was built. The tickets were sold. Nobody asked the neighbors.',
    affectedZoneIds: ['open_lawn'],
    difficulty: 10,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 2,
      resourceCost: { influence: 2, volunteer: 1 },
      abilityChecks: [
        { ability: 'communityTrust', threshold: 11, skill: 'negotiation' },
      ],
    },
    failureConsequences: [
      { type: 'cws_penalty', params: { amount: 2 } },
      { type: 'new_problem', params: { zoneId: 'open_lawn', problem: 'community_resentment' } },
    ],
    successRewards: [
      { type: 'cws_bonus', params: { amount: 2 } },
      { type: 'cp_bonus', params: { amount: 2 } },
      { type: 'resource_gain', params: { resources: { budget: 2 } } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'social',
    artworkId: 'art_ch_event_permit',
  },
  {
    id: 'ch_gen_27',
    name: 'Soil Erosion',
    description: 'Runoff and poor drainage are causing soil erosion in multiple zones, threatening plants and structures.',
    flavorText: 'The topsoil washed away with the rain. Beneath it, only clay and rocks remained.',
    affectedZoneIds: ['herbal_garden', 'open_lawn'],
    difficulty: 11,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 1,
      resourceCost: { material: 3, knowledge: 1 },
      abilityChecks: [
        { ability: 'technicalKnowledge', threshold: 10, skill: 'environmentalAssessment' },
      ],
    },
    failureConsequences: [
      { type: 'zone_degrade', params: { zoneId: 'herbal_garden', levels: 1 } },
      { type: 'cws_penalty', params: { amount: 2 } },
    ],
    successRewards: [
      { type: 'cws_bonus', params: { amount: 2 } },
      { type: 'cp_bonus', params: { amount: 2 } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'ecological',
    artworkId: 'art_ch_soil_erosion',
  },
  {
    id: 'ch_gen_28',
    name: 'Security Camera System Failure',
    description: 'The park security system has failed. Anti-social behavior is on the rise without surveillance.',
    flavorText: 'The screens went black. So did the sense of safety.',
    affectedZoneIds: ['main_entrance', 'fiber_optic_lane'],
    difficulty: 9,
    requirements: {
      minSeriesLength: 2,
      minUniqueRoles: 1,
      resourceCost: { budget: 2, material: 1 },
      abilityChecks: [
        { ability: 'resourcefulness', threshold: 9 },
      ],
    },
    failureConsequences: [
      { type: 'cws_penalty', params: { amount: 2 } },
      { type: 'new_problem', params: { zoneId: 'main_entrance', problem: 'security_failure' } },
    ],
    successRewards: [
      { type: 'cws_bonus', params: { amount: 2 } },
      { type: 'cp_bonus', params: { amount: 1 } },
    ],
    escalationPerRound: 1,
    roundsActive: 0,
    category: 'safety',
    artworkId: 'art_ch_security',
  },
  {
    id: 'ch_gen_29',
    name: 'Festival Planning Crisis',
    description: 'The annual park festival is approaching with no plan, no budget, and no coordination. Failure would be embarrassing for all.',
    flavorText: 'The festival was in two weeks. The planning committee had met once. In their minds.',
    affectedZoneIds: ['open_lawn', 'vendor_hub', 'fountain_plaza'],
    difficulty: 12,
    requirements: {
      minSeriesLength: 3,
      minUniqueRoles: 3,
      resourceCost: { budget: 3, volunteer: 2, influence: 1 },
      abilityChecks: [
        { ability: 'adaptability', threshold: 11, skill: 'coalitionBuilding' },
      ],
    },
    failureConsequences: [
      { type: 'cws_penalty', params: { amount: 3 } },
      { type: 'resource_loss', params: { resources: { influence: 2 } } },
    ],
    successRewards: [
      { type: 'cws_bonus', params: { amount: 4 } },
      { type: 'cp_bonus', params: { amount: 3 } },
      { type: 'resource_gain', params: { resources: { budget: 3, volunteer: 2 } } },
    ],
    escalationPerRound: 2,
    roundsActive: 0,
    category: 'social',
    artworkId: 'art_ch_festival',
  },
  {
    id: 'ch_gen_30',
    name: 'Groundwater Contamination',
    description: 'Testing reveals groundwater contamination affecting the boating pond and herbal garden irrigation.',
    flavorText: 'The water looked clear. The lab report said otherwise.',
    affectedZoneIds: ['boating_pond', 'herbal_garden'],
    difficulty: 14,
    requirements: {
      minSeriesLength: 3,
      minUniqueRoles: 2,
      resourceCost: { budget: 4, knowledge: 2 },
      abilityChecks: [
        { ability: 'technicalKnowledge', threshold: 12, skill: 'environmentalAssessment' },
        { ability: 'authority', threshold: 10 },
      ],
    },
    failureConsequences: [
      { type: 'zone_degrade', params: { zoneId: 'boating_pond', levels: 1 } },
      { type: 'zone_degrade', params: { zoneId: 'herbal_garden', levels: 1 } },
      { type: 'cws_penalty', params: { amount: 4 } },
    ],
    successRewards: [
      { type: 'cws_bonus', params: { amount: 4 } },
      { type: 'cp_bonus', params: { amount: 3 } },
      { type: 'resource_gain', params: { resources: { knowledge: 2 } } },
    ],
    escalationPerRound: 2,
    roundsActive: 0,
    category: 'ecological',
    artworkId: 'art_ch_groundwater',
  },
];

export const ALL_CHALLENGES: ChallengeCard[] = [...SITE_CHALLENGES, ...GENERIC_CHALLENGES];
