import { EventCard } from '../models/types';

export const EVENT_CARDS: EventCard[] = [
  // 10 Negative Events
  {
    id: 'evt_neg_01',
    name: 'Unseasonal Storm',
    description: 'A sudden storm damages outdoor structures and floods low-lying zones. All outdoor zones lose 1 progress marker.',
    flavorText: 'The sky turned black at noon. By evening, the park was a lake.',
    type: 'negative',
    effects: [
      { type: 'add_problem_marker', target: 'open_lawn', params: { count: 1 } },
      { type: 'add_problem_marker', target: 'walking_track', params: { count: 1 } },
      { type: 'modify_zone_condition', target: 'boating_pond', params: { degradeLevels: 1 } },
    ],
    artworkId: 'art_evt_storm',
  },
  {
    id: 'evt_neg_02',
    name: 'Municipal Election Freeze',
    description: 'An upcoming election freezes all government approvals and budget allocations for this round.',
    flavorText: 'The files gathered dust on the desk. Nobody would sign anything until after the election.',
    type: 'negative',
    effects: [
      { type: 'modify_player_ability_temp', target: 'administrator', params: { ability: 'authority', modifier: -3, duration: 1 } },
      { type: 'modify_difficulty', target: 'all', params: { amount: 2 } },
    ],
    artworkId: 'art_evt_election',
  },
  {
    id: 'evt_neg_03',
    name: 'Contractor Scandal',
    description: 'A major contractor is caught using substandard materials. All construction progress this round is halved.',
    flavorText: 'The cement was mixed with river sand. The pillars crumbled like biscuits.',
    type: 'negative',
    effects: [
      { type: 'modify_difficulty', target: 'all', params: { amount: 2, category: 'infrastructure' } },
      { type: 'remove_resources_from_zone', target: 'ppp_zone', params: { resources: { material: 1 } } },
    ],
    artworkId: 'art_evt_contractor_scandal',
  },
  {
    id: 'evt_neg_04',
    name: 'Anti-Social Behavior Wave',
    description: 'A surge in anti-social behavior including vandalism and littering affects the most-visited zones.',
    flavorText: 'Graffiti on the walls. Broken bottles on the path. The park felt hostile.',
    type: 'negative',
    effects: [
      { type: 'add_problem_marker', target: 'playground', params: { count: 1 } },
      { type: 'add_problem_marker', target: 'open_lawn', params: { count: 1 } },
      { type: 'modify_player_ability_temp', target: 'citizen', params: { ability: 'communityTrust', modifier: -2, duration: 1 } },
    ],
    artworkId: 'art_evt_antisocial',
  },
  {
    id: 'evt_neg_05',
    name: 'Budget Sequestration',
    description: 'Central government orders a budget cut. All players with Budget tokens lose 1 immediately.',
    flavorText: 'The circular arrived at 5 PM on Friday. Effective immediately. No appeals.',
    type: 'negative',
    effects: [
      { type: 'add_resources_to_player', target: 'all', params: { resources: { budget: -1 } } },
    ],
    artworkId: 'art_evt_sequestration',
  },
  {
    id: 'evt_neg_06',
    name: 'Viral Social Media Backlash',
    description: 'A negative viral post about park conditions reduces community trust and political leverage for everyone.',
    flavorText: 'The video of the overflowing drain had two million views by lunch.',
    type: 'negative',
    effects: [
      { type: 'modify_player_ability_temp', target: 'all', params: { ability: 'communityTrust', modifier: -2, duration: 1 } },
      { type: 'modify_player_ability_temp', target: 'administrator', params: { ability: 'politicalLeverage', modifier: -2, duration: 1 } },
    ],
    artworkId: 'art_evt_social_media',
  },
  {
    id: 'evt_neg_07',
    name: 'Supply Chain Disruption',
    description: 'Global supply chain issues make construction materials scarce and expensive this round.',
    flavorText: 'The shipment was delayed. Again. The price had doubled. Again.',
    type: 'negative',
    effects: [
      { type: 'add_resources_to_player', target: 'all', params: { resources: { material: -1 } } },
      { type: 'modify_difficulty', target: 'all', params: { amount: 1, category: 'infrastructure' } },
    ],
    artworkId: 'art_evt_supply_chain',
  },
  {
    id: 'evt_neg_08',
    name: 'Health Scare',
    description: 'A reported illness linked to park water sources causes visitor numbers to plummet. Revenue drops.',
    flavorText: 'The hospital report mentioned the park. The gates emptied within hours.',
    type: 'negative',
    effects: [
      { type: 'add_problem_marker', target: 'boating_pond', params: { count: 1 } },
      { type: 'add_resources_to_player', target: 'investor', params: { resources: { budget: -2 } } },
      { type: 'block_zone', target: 'boating_pond', params: { duration: 1 } },
    ],
    artworkId: 'art_evt_health_scare',
  },
  {
    id: 'evt_neg_09',
    name: 'Key Official Transfer',
    description: 'A supportive government official is transferred. Their replacement is indifferent to the park.',
    flavorText: 'The IAS officer who cared was posted to another district. The replacement had other priorities.',
    type: 'negative',
    effects: [
      { type: 'modify_player_ability_temp', target: 'administrator', params: { ability: 'politicalLeverage', modifier: -3, duration: 2 } },
      { type: 'modify_difficulty', target: 'all', params: { amount: 1 } },
    ],
    artworkId: 'art_evt_official_transfer',
  },
  {
    id: 'evt_neg_10',
    name: 'Encroachment Escalation',
    description: 'Unauthorized construction encroaches on park boundaries. Legal battles consume resources.',
    flavorText: 'The fence had moved ten feet overnight. Behind it, a concrete slab was already poured.',
    type: 'negative',
    effects: [
      { type: 'add_problem_marker', target: 'main_entrance', params: { count: 1 } },
      { type: 'add_problem_marker', target: 'ppp_zone', params: { count: 1 } },
      { type: 'add_resources_to_player', target: 'administrator', params: { resources: { influence: -1 } } },
    ],
    artworkId: 'art_evt_encroachment',
  },

  // 10 Positive Events
  {
    id: 'evt_pos_01',
    name: 'Celebrity Park Visit',
    description: 'A famous personality visits the park and posts positively on social media. All zones get a visibility boost.',
    flavorText: 'The actress sat on the bench, took a selfie, and half a million people suddenly cared about the park.',
    type: 'positive',
    effects: [
      { type: 'modify_player_ability_temp', target: 'all', params: { ability: 'communityTrust', modifier: 2, duration: 1 } },
      { type: 'grant_tokens', target: 'all', params: { resources: { influence: 1 } } },
    ],
    artworkId: 'art_evt_celebrity',
  },
  {
    id: 'evt_pos_02',
    name: 'State Government Grant',
    description: 'The state government announces a special grant for urban green spaces. Additional funding available.',
    flavorText: 'The Chief Minister had a soft spot for parks. Thank goodness.',
    type: 'positive',
    effects: [
      { type: 'add_resources_to_player', target: 'administrator', params: { resources: { budget: 3 } } },
      { type: 'grant_tokens', target: 'advocate', params: { resources: { budget: 2 } } },
    ],
    artworkId: 'art_evt_govt_grant',
  },
  {
    id: 'evt_pos_03',
    name: 'Corporate CSR Initiative',
    description: 'A major corporation selects the park for its CSR program. Material donations and volunteer support arrive.',
    flavorText: 'The trucks arrived with paint, benches, and twenty enthusiastic volunteers in matching t-shirts.',
    type: 'positive',
    effects: [
      { type: 'grant_tokens', target: 'investor', params: { resources: { material: 3, volunteer: 2 } } },
      { type: 'double_cws_this_round', target: 'all', params: {} },
    ],
    artworkId: 'art_evt_csr',
  },
  {
    id: 'evt_pos_04',
    name: 'University Partnership',
    description: 'A local university offers to study and assist with park ecology. Free expertise and student volunteers.',
    flavorText: 'The professor said this could be a living laboratory. The students were already collecting samples.',
    type: 'positive',
    effects: [
      { type: 'grant_tokens', target: 'designer', params: { resources: { knowledge: 2 } } },
      { type: 'grant_tokens', target: 'advocate', params: { resources: { knowledge: 2 } } },
      { type: 'add_resources_to_player', target: 'citizen', params: { resources: { volunteer: 2 } } },
    ],
    artworkId: 'art_evt_university',
  },
  {
    id: 'evt_pos_05',
    name: 'Favorable Court Ruling',
    description: 'A court ruling protects the park from encroachment and mandates improvements. Legal backing secured.',
    flavorText: 'The gavel fell. The park was protected. For now.',
    type: 'positive',
    effects: [
      { type: 'remove_problem_marker', target: 'main_entrance', params: { count: 1 } },
      { type: 'modify_player_ability_temp', target: 'advocate', params: { ability: 'politicalLeverage', modifier: 3, duration: 2 } },
      { type: 'grant_tokens', target: 'administrator', params: { resources: { influence: 2 } } },
    ],
    artworkId: 'art_evt_court_ruling',
  },
  {
    id: 'evt_pos_06',
    name: 'International Recognition',
    description: 'An international urban planning journal features the park as a case study. Prestige and attention follow.',
    flavorText: 'Page 34 of Urban Planning Quarterly. The paragraph was short. The impact was not.',
    type: 'positive',
    effects: [
      { type: 'modify_player_ability_temp', target: 'designer', params: { ability: 'technicalKnowledge', modifier: 3, duration: 2 } },
      { type: 'grant_tokens', target: 'all', params: { resources: { knowledge: 1 } } },
    ],
    artworkId: 'art_evt_international',
  },
  {
    id: 'evt_pos_07',
    name: 'Volunteer Surge',
    description: 'A viral cleanup challenge inspires hundreds of volunteers to sign up for park improvement projects.',
    flavorText: 'The hashtag spread faster than anyone expected. By Saturday, three hundred people showed up.',
    type: 'positive',
    effects: [
      { type: 'add_resources_to_player', target: 'citizen', params: { resources: { volunteer: 3 } } },
      { type: 'grant_tokens', target: 'all', params: { resources: { volunteer: 1 } } },
    ],
    artworkId: 'art_evt_volunteer_surge',
  },
  {
    id: 'evt_pos_08',
    name: 'Material Donation',
    description: 'A closing construction company donates surplus building materials to the park. Free resources for all.',
    flavorText: 'Their loss was the park\'s gain. Bricks, tiles, pipes, and enough paint for a year.',
    type: 'positive',
    effects: [
      { type: 'grant_tokens', target: 'designer', params: { resources: { material: 3 } } },
      { type: 'grant_tokens', target: 'investor', params: { resources: { material: 2 } } },
    ],
    artworkId: 'art_evt_material_donation',
  },
  {
    id: 'evt_pos_09',
    name: 'Festival Revenue Windfall',
    description: 'An unexpectedly successful festival generates surplus revenue that can be reinvested in the park.',
    flavorText: 'The food stalls sold out by noon. The concert ran till midnight. Everyone went home happy.',
    type: 'positive',
    effects: [
      { type: 'add_resources_to_player', target: 'investor', params: { resources: { budget: 3 } } },
      { type: 'add_resources_to_player', target: 'administrator', params: { resources: { budget: 2 } } },
      { type: 'modify_player_ability_temp', target: 'citizen', params: { ability: 'communityTrust', modifier: 2, duration: 1 } },
    ],
    artworkId: 'art_evt_festival_revenue',
  },
  {
    id: 'evt_pos_10',
    name: 'NGO Collaboration',
    description: 'A well-funded environmental NGO offers to partner on park restoration. Technical expertise and funding available.',
    flavorText: 'The email from the NGO headquarters was brief: We want to help. When can we start?',
    type: 'positive',
    effects: [
      { type: 'grant_tokens', target: 'advocate', params: { resources: { budget: 2, knowledge: 2, influence: 1 } } },
      { type: 'modify_player_ability_temp', target: 'all', params: { ability: 'adaptability', modifier: 1, duration: 2 } },
    ],
    artworkId: 'art_evt_ngo',
  },
];
