import { Zone, TriggerTile } from '../models/types';

export const ZONES: Record<string, Zone> = {
  main_entrance: {
    id: 'main_entrance',
    name: 'Main Entrance & Parking',
    description: 'The primary gateway to the eco-park. Handles visitor flow, ticketing, and first impressions. Vendor encroachment is a persistent issue.',
    gridPosition: { q: 0, r: 0 },
    condition: 'fair',
    conditionHistory: [],
    resources: { budget: 1, influence: 0, volunteer: 2, material: 1, knowledge: 0 },
    activeProblems: ['vendor_encroachment'],
    progressMarkers: 0,
    problemMarkers: 0,
    playerStandees: [],
    revealedTrigger: null,
    isLocked: false,
    zoneType: 'administrative',
    specialProperties: {},
    primaryResourceType: 'budget',
    poolType: 'owned',
    investedThisRound: false,
  },
  fountain_plaza: {
    id: 'fountain_plaza',
    name: 'Fountain Plaza',
    description: 'A once-grand ornamental fountain area that has fallen into disrepair. The broken fountain is both an eyesore and a symbol of neglect.',
    gridPosition: { q: 1, r: 0 },
    condition: 'poor',
    conditionHistory: [],
    resources: { budget: 1, influence: 0, volunteer: 0, material: 0, knowledge: 0 },
    activeProblems: ['fountain_failure'],
    progressMarkers: 0,
    problemMarkers: 0,
    playerStandees: [],
    revealedTrigger: null,
    isLocked: false,
    zoneType: 'cultural',
    specialProperties: {},
    primaryResourceType: 'budget',
    poolType: 'owned',
    investedThisRound: false,
  },
  boating_pond: {
    id: 'boating_pond',
    name: 'Boating Pond',
    description: 'A large water body suffering from severe algae bloom and pollution. Once a popular boating attraction, now an ecological crisis zone.',
    gridPosition: { q: 2, r: 0 },
    condition: 'critical',
    conditionHistory: [],
    resources: { budget: 0, influence: 0, volunteer: 0, material: 0, knowledge: 0 },
    activeProblems: ['algae_bloom'],
    progressMarkers: 0,
    problemMarkers: 0,
    playerStandees: [],
    revealedTrigger: null,
    isLocked: false,
    zoneType: 'ecological',
    specialProperties: {},
    primaryResourceType: 'volunteer',
    // Fix 1: Common Pool Zone
    poolType: 'common',
    commonPoolConfig: {
      resourceType: 'volunteer',
      tokenName: 'Aqua Credits',
      generatedBy: ['advocate', 'citizen'],
      consumedBy: ['designer', 'investor'],
      autoIncomePerRound: 1,
      decayPerRoundIfNeglected: 1,
    },
    investedThisRound: false,
  },
  playground: {
    id: 'playground',
    name: "Children's Playground",
    description: 'A playground with aging equipment and safety concerns. Parents are worried but children still flock here daily.',
    gridPosition: { q: 3, r: 0 },
    condition: 'poor',
    conditionHistory: [],
    resources: { budget: 0, influence: 0, volunteer: 1, material: 0, knowledge: 0 },
    activeProblems: ['playground_safety'],
    progressMarkers: 0,
    problemMarkers: 0,
    playerStandees: [],
    revealedTrigger: null,
    isLocked: false,
    zoneType: 'recreation',
    specialProperties: {},
    primaryResourceType: 'volunteer',
    poolType: 'owned',
    investedThisRound: false,
  },
  walking_track: {
    id: 'walking_track',
    name: 'Walking Track',
    description: 'A perimeter path used by morning walkers and joggers. Broken footpaths and poor lighting make it less accessible after dark.',
    gridPosition: { q: 4, r: 0 },
    condition: 'fair',
    conditionHistory: [],
    resources: { budget: 0, influence: 0, volunteer: 2, material: 0, knowledge: 0 },
    activeProblems: ['broken_footpaths'],
    progressMarkers: 0,
    problemMarkers: 0,
    playerStandees: [],
    revealedTrigger: null,
    isLocked: false,
    zoneType: 'recreation',
    specialProperties: {},
    primaryResourceType: 'volunteer',
    poolType: 'owned',
    investedThisRound: false,
  },
  herbal_garden: {
    id: 'herbal_garden',
    name: 'Herbal Garden',
    description: 'A curated medicinal plant garden maintained by local enthusiasts. Irrigation issues threaten its survival despite good overall condition.',
    gridPosition: { q: 0, r: 1 },
    condition: 'good',
    conditionHistory: [],
    resources: { budget: 0, influence: 0, volunteer: 0, material: 1, knowledge: 1 },
    activeProblems: ['irrigation_failure'],
    progressMarkers: 0,
    problemMarkers: 0,
    playerStandees: [],
    revealedTrigger: null,
    isLocked: false,
    zoneType: 'ecological',
    specialProperties: {},
    primaryResourceType: 'knowledge',
    poolType: 'owned',
    investedThisRound: false,
  },
  open_lawn: {
    id: 'open_lawn',
    name: 'Open Lawn',
    description: 'A large green expanse used for community gatherings, yoga sessions, and informal sports. Needs better seating and shade.',
    gridPosition: { q: 1, r: 1 },
    condition: 'good',
    conditionHistory: [],
    resources: { budget: 0, influence: 0, volunteer: 3, material: 0, knowledge: 0 },
    activeProblems: ['inadequate_seating'],
    progressMarkers: 0,
    problemMarkers: 0,
    playerStandees: [],
    revealedTrigger: null,
    isLocked: false,
    zoneType: 'recreation',
    specialProperties: {},
    primaryResourceType: 'volunteer',
    poolType: 'owned',
    investedThisRound: false,
  },
  exercise_zone: {
    id: 'exercise_zone',
    name: 'Exercise Zone',
    description: 'An outdoor gym area with exercise equipment in varying states of repair. Popular with fitness enthusiasts of all ages.',
    gridPosition: { q: 2, r: 1 },
    condition: 'fair',
    conditionHistory: [],
    resources: { budget: 0, influence: 0, volunteer: 0, material: 1, knowledge: 0 },
    activeProblems: ['equipment_wear'],
    progressMarkers: 0,
    problemMarkers: 0,
    playerStandees: [],
    revealedTrigger: null,
    isLocked: false,
    zoneType: 'recreation',
    specialProperties: {},
    primaryResourceType: 'material',
    poolType: 'owned',
    investedThisRound: false,
  },
  sculpture_garden: {
    id: 'sculpture_garden',
    name: 'Sculpture Garden',
    description: 'A tranquil area featuring local art installations. Well-maintained and a point of civic pride.',
    gridPosition: { q: 3, r: 1 },
    condition: 'good',
    conditionHistory: [],
    resources: { budget: 0, influence: 0, volunteer: 0, material: 0, knowledge: 1 },
    activeProblems: [],
    progressMarkers: 0,
    problemMarkers: 0,
    playerStandees: [],
    revealedTrigger: null,
    isLocked: false,
    zoneType: 'cultural',
    specialProperties: {},
    primaryResourceType: 'knowledge',
    poolType: 'owned',
    investedThisRound: false,
  },
  vendor_hub: {
    id: 'vendor_hub',
    name: 'Vendor Hub',
    description: 'A cluster of food stalls and small shops. Revenue-generating but quality control and hygiene are ongoing concerns.',
    gridPosition: { q: 4, r: 1 },
    condition: 'fair',
    conditionHistory: [],
    resources: { budget: 2, influence: 0, volunteer: 0, material: 0, knowledge: 0 },
    activeProblems: ['vendor_quality'],
    progressMarkers: 0,
    problemMarkers: 0,
    playerStandees: [],
    revealedTrigger: null,
    isLocked: false,
    zoneType: 'commercial',
    specialProperties: {},
    primaryResourceType: 'budget',
    poolType: 'owned',
    investedThisRound: false,
  },
  restroom_block: {
    id: 'restroom_block',
    name: 'Restroom Block',
    description: 'Public facilities in poor condition. Frequent breakdowns and hygiene complaints make this a priority for many visitors.',
    gridPosition: { q: 0, r: 2 },
    condition: 'poor',
    conditionHistory: [],
    resources: { budget: 0, influence: 0, volunteer: 0, material: 0, knowledge: 0 },
    activeProblems: ['restroom_failure'],
    progressMarkers: 0,
    problemMarkers: 0,
    playerStandees: [],
    revealedTrigger: null,
    isLocked: false,
    zoneType: 'utility',
    specialProperties: {},
    primaryResourceType: 'material',
    // Fix 1: Common Pool Zone
    poolType: 'common',
    commonPoolConfig: {
      resourceType: 'material',
      tokenName: 'Civic Tokens',
      generatedBy: ['administrator'],
      consumedBy: ['citizen', 'designer'],
      autoIncomePerRound: 1,
      decayPerRoundIfNeglected: 1,
    },
    investedThisRound: false,
  },
  fiber_optic_lane: {
    id: 'fiber_optic_lane',
    name: 'Fiber Optic Lane',
    description: 'A pathway lined with LED light installations and digital displays. Some lights have failed, dimming the evening experience.',
    gridPosition: { q: 1, r: 2 },
    condition: 'fair',
    conditionHistory: [],
    resources: { budget: 0, influence: 0, volunteer: 0, material: 1, knowledge: 0 },
    activeProblems: ['led_failures'],
    progressMarkers: 0,
    problemMarkers: 0,
    playerStandees: [],
    revealedTrigger: null,
    isLocked: false,
    zoneType: 'cultural',
    specialProperties: {},
    primaryResourceType: 'material',
    poolType: 'owned',
    investedThisRound: false,
  },
  ppp_zone: {
    id: 'ppp_zone',
    name: 'PPP Development Zone',
    description: 'A zone earmarked for public-private partnership development. Currently stalled due to regulatory and funding disagreements.',
    gridPosition: { q: 2, r: 2 },
    condition: 'fair',
    conditionHistory: [],
    resources: { budget: 0, influence: 0, volunteer: 0, material: 0, knowledge: 0 },
    activeProblems: ['stalled_development'],
    progressMarkers: 0,
    problemMarkers: 0,
    playerStandees: [],
    revealedTrigger: null,
    isLocked: false,
    zoneType: 'development',
    specialProperties: {},
    primaryResourceType: 'budget',
    // Fix 1: Common Pool Zone
    poolType: 'common',
    commonPoolConfig: {
      resourceType: 'budget',
      tokenName: 'Bond Chips',
      generatedBy: ['investor'],
      consumedBy: ['administrator', 'designer'],
      autoIncomePerRound: 1,
      decayPerRoundIfNeglected: 1,
    },
    investedThisRound: false,
  },
  maintenance_depot: {
    id: 'maintenance_depot',
    name: 'Maintenance Depot',
    description: 'The operational backbone of the park. Understaffed and under-resourced, impacting maintenance across all zones.',
    gridPosition: { q: 3, r: 2 },
    condition: 'poor',
    conditionHistory: [],
    resources: { budget: 1, influence: 0, volunteer: 0, material: 2, knowledge: 0 },
    activeProblems: ['understaffed'],
    progressMarkers: 0,
    problemMarkers: 0,
    playerStandees: [],
    revealedTrigger: null,
    isLocked: false,
    zoneType: 'administrative',
    specialProperties: {},
    primaryResourceType: 'material',
    poolType: 'owned',
    investedThisRound: false,
  },
};

export const ADJACENCY: Record<string, string[]> = {
  main_entrance: ['fountain_plaza', 'herbal_garden', 'open_lawn'],
  fountain_plaza: ['main_entrance', 'boating_pond', 'open_lawn', 'herbal_garden'],
  boating_pond: ['fountain_plaza', 'playground', 'open_lawn', 'exercise_zone'],
  playground: ['boating_pond', 'walking_track', 'exercise_zone', 'sculpture_garden'],
  walking_track: ['playground', 'sculpture_garden', 'vendor_hub'],
  herbal_garden: ['main_entrance', 'fountain_plaza', 'open_lawn', 'restroom_block'],
  open_lawn: ['main_entrance', 'fountain_plaza', 'boating_pond', 'herbal_garden', 'exercise_zone', 'fiber_optic_lane'],
  exercise_zone: ['boating_pond', 'playground', 'open_lawn', 'sculpture_garden', 'fiber_optic_lane', 'ppp_zone'],
  sculpture_garden: ['playground', 'walking_track', 'exercise_zone', 'vendor_hub', 'ppp_zone', 'maintenance_depot'],
  vendor_hub: ['walking_track', 'sculpture_garden', 'maintenance_depot'],
  restroom_block: ['herbal_garden', 'fiber_optic_lane'],
  fiber_optic_lane: ['open_lawn', 'exercise_zone', 'restroom_block', 'ppp_zone'],
  ppp_zone: ['exercise_zone', 'sculpture_garden', 'fiber_optic_lane', 'maintenance_depot'],
  maintenance_depot: ['sculpture_garden', 'vendor_hub', 'ppp_zone'],
};

export const TRIGGER_TILES: Record<string, TriggerTile> = {
  trigger_hidden_spring: {
    id: 'trigger_hidden_spring',
    zoneId: 'herbal_garden',
    type: 'secret_door',
    revealed: false,
    title: 'Hidden Natural Spring',
    description: 'A forgotten natural spring is discovered beneath the herbal garden. It can supply water to adjacent zones, solving irrigation problems permanently.',
    effects: [
      { type: 'cascade_positive', targetZoneId: 'herbal_garden', params: { removeProblems: ['irrigation_failure'], description: 'Natural spring resolves irrigation' } },
      { type: 'add_resources', targetZoneId: 'herbal_garden', params: { resources: { volunteer: 2, knowledge: 1 } } },
      { type: 'cascade_positive', targetZoneId: 'boating_pond', params: { addProgress: 2, description: 'Fresh water feeds into boating pond' } },
    ],
  },
  trigger_buried_waste: {
    id: 'trigger_buried_waste',
    zoneId: 'ppp_zone',
    type: 'trap',
    revealed: false,
    title: 'Buried Construction Waste',
    description: 'Construction begins only to uncover illegally buried waste from a previous development. Cleanup is mandatory before any work can proceed.',
    effects: [
      { type: 'add_problem', targetZoneId: 'ppp_zone', params: { problem: 'toxic_waste_cleanup', description: 'Buried waste discovered during excavation' } },
      { type: 'waste_resources', params: { resources: { budget: 3, material: 2 }, description: 'Emergency cleanup costs' } },
      { type: 'cascade_negative', targetZoneId: 'exercise_zone', params: { addProblemMarkers: 1, description: 'Contamination risk spreads to adjacent zone' } },
    ],
  },
  trigger_heritage_artifact: {
    id: 'trigger_heritage_artifact',
    zoneId: 'sculpture_garden',
    type: 'secret_door',
    revealed: false,
    title: 'Heritage Artifact Discovery',
    description: 'During landscaping, workers unearth a historically significant artifact. This could boost the cultural value of the park significantly.',
    effects: [
      { type: 'cascade_positive', targetZoneId: 'sculpture_garden', params: { addProgress: 3, description: 'Heritage discovery boosts cultural significance' } },
      { type: 'grant_tokens', params: { resources: { knowledge: 2, influence: 1 }, description: 'Media attention and academic interest' } },
      { type: 'unlock_grant', params: { grantAmount: 4, description: 'Heritage preservation grant unlocked' } },
    ],
  },
  trigger_pipe_burst: {
    id: 'trigger_pipe_burst',
    zoneId: 'restroom_block',
    type: 'cascading_effect',
    revealed: false,
    title: 'Underground Pipe Burst',
    description: 'A major underground water pipe bursts, flooding the restroom block and threatening adjacent zones with water damage.',
    effects: [
      { type: 'cascade_negative', targetZoneId: 'restroom_block', params: { degradeCondition: true, description: 'Flooding damages restroom facilities further' } },
      { type: 'cascade_negative', targetZoneId: 'herbal_garden', params: { addProblemMarkers: 1, description: 'Waterlogging threatens herbal garden plants' } },
      { type: 'cascade_negative', targetZoneId: 'fiber_optic_lane', params: { addProblemMarkers: 1, description: 'Water damage to electrical installations' } },
      { type: 'add_problem', targetZoneId: 'restroom_block', params: { problem: 'flooding', description: 'Severe flooding from pipe burst' } },
    ],
  },
};
